### ISSUE TITLE
Keeping timestamp of original event

### ISSUE THREAD

**Issue by bohyn** [fluent/fluent-plugin-kafka#100]
As from my observations, log records passed through kafka in/out plugin are loosing their original timestamp. Instead of it, messages produced by *kafka_in* plugin have timestamp set with the actual time they are read from kafka. It is done on this row in source code:

https://github.com/fluent/fluent-plugin-kafka/blob/master/lib/fluent/plugin/in_kafka.rb#L234

> es.add(Fluent::Engine.now, @parser.call(msg, @topic_entry))

May I ask why is it behaving like this? Wouldn't it be more logical to keep the datetime of original event?

**Comment by repeatedly** [comment]
Using record's timestamp seems good.

**Comment by bohyn** [comment]
Ok, I have prepared fix. Do you want me to push it for pull request in your repository? I do not have permission to create new branches here.
