### ISSUE TITLE
Send data to kafka over secure TLS/HTTPS

### ISSUE THREAD

**Issue by iam404** [fluent/fluent-plugin-kafka#104]
Hi Team

I have looked over the documentation provided but still could not figure out how to establish connection b/w fluent <--> kafka securely.

**Comment by repeatedly** [comment]
Try these parameters: https://github.com/fluent/fluent-plugin-kafka/blob/c14c1c5ce9c71cb84c2badd33f46c4d527fee8d7/lib/fluent/plugin/kafka_plugin_util.rb#L6

**Comment by repeatedly** [comment]
Added parameters: https://github.com/fluent/fluent-plugin-kafka#common-parameters
