### ISSUE TITLE
Timestamp support with kafka 0.10

### ISSUE THREAD

**Issue by javefang** [fluent/fluent-plugin-kafka#106]
Hi,

Kafka 0.10 starts to support message timstamp now. Is there plan to expose that in the plugin?

Thanks,
Xinghong

**Comment by repeatedly** [comment]
fluent-plugin-kafka depends on ruby-kafka and ruby-kafka doesn't support message timstampe yet.

https://github.com/zendesk/ruby-kafka/pull/279

**Comment by javefang** [comment]
Thank you for pointing this out, will keep an eye on it :)

**Comment by az3** [comment]
Until that support comes, you can use LogAppendTime in your topic configuration to see the timestamp values in consumers.
```
bin/kafka-configs --alter --entity-name test_topic --entity-type topics --add-config message.timestamp.type=LogAppendTime --zookeeper localhost:2181
```

**Comment by CoufalJa** [comment]
https://github.com/zendesk/ruby-kafka/pull/279 was closed and message timestamp is available since version 0.4.0.

**Comment by repeatedly** [comment]
No. timestamp support is not available in v0.4.0.
v0.5.0 will support it.

**Comment by hctech** [comment]
timestamp can support milliseconds?

**Comment by cosmo0920** [comment]
Yes. https://github.com/zendesk/ruby-kafka/pull/279/files#diff-9f7d81a7eccc8b28ac412ad09bbe7ddfR83
Kafka 0.10 API's timestamp resolution is milliseconds:
https://issues.apache.org/jira/browse/KAFKA-3025

**Comment by JakubCoufal** [comment]
So ruby-kafka 0.5.0 was finally released with timestamp support, any plans to upgrade?

**Comment by repeatedly** [comment]
After back from kubecon, I will add timestamp support.

**Comment by leedohyun** [comment]
Hi! repeatedly :) 
I'm so sorry to bother you.
But any plans to upgrade?

**Comment by repeatedly** [comment]
In the last month, ruby-kafka 0.5.2 finally supported producer timestamp.
So we can add it.

**Comment by leedohyun** [comment]
@repeatedly 
Thank you for your reply 👍

**Comment by jaynblue** [comment]
@repeatedly
 
Is there a plan to fix the issue?

**Comment by jaynblue** [comment]
@repeatedly
Is there a plan to fix the issue?

**Comment by kenhys** [comment]
time_source was supported since v0.12.1
