### ISSUE TITLE
Parsing broker hosts/ports from zookeeper should refer to "endpoints" section.

### ISSUE THREAD

**Issue by saturday-shi** [fluent/fluent-plugin-kafka#112]
If some authentication framework like SASL was used in Kafka, broker hosts/ports would be registered to zookeeper in `endpoints` section. That is, left `host` and `port` with default value null and -1 ([KAFKA-3948](https://issues.apache.org/jira/browse/KAFKA-3948)). e.g.:
```
{"jmx_port":9393,"timestamp":"1487207559594","endpoints":["SASL_PLAINTEXT://host003.test.local:9092"],"host":null,"version":3,"port":-1}
```

Thus, [the latest code for now](https://github.com/fluent/fluent-plugin-kafka/blob/master/lib/fluent/plugin/out_kafka_buffered.rb#L94) will result in a list of `[":-1", ":-1", ...]`. We should look under endpoints section while parsing broker hosts/ports from zookeeper.

**Comment by repeatedly** [comment]
Ah, I first knew this behaviour.
Using zookeeper is hard...

**Comment by saturday-shi** [comment]
I hadn't known about this util I attempted to enable Kerberos in my cluster.
This is not a big problem for now but maybe helpful when you add something like Kerberos supporting in the future :)
