### ISSUE TITLE
output_data_type avro support

### ISSUE THREAD

**Issue by CBR09** [fluent/fluent-plugin-kafka#114]
I want to use fluentd output to Kafka in Avro, can Avro be supported?, according to Avro document, Avro provide:
```
Rich data structures.
A compact, fast, binary data format.
A container file, to store persistent data.
Remote procedure call (RPC).
Simple integration with dynamic languages. Code generation is not required to read or write data files nor to use or implement RPC protocols. Code generation as an optional optimization, only worth implementing for statically typed languages.
```

**Comment by repeatedly** [comment]
https://github.com/takebayashi/fluent-plugin-avro may work.

**Comment by CBR09** [comment]
@repeatedly , sorry for late response, I've tried with that, but no luck, fluent-plugin-avro outdated

**Comment by kenhys** [comment]
https://github.com/mstinglin/fluent-plugin-avro may work (it contains additional commit https://github.com/mstinglin/fluent-plugin-avro/commit/db2d5b73ea19c32ee5da916497465ffca9189c16)
