### ISSUE TITLE
Kerberos Support

### ISSUE THREAD

**Issue by johnseekins** [fluent/fluent-plugin-kafka#115]
It would be really nice to have kerberos support in this plugin (as mentioned - briefly - in #44).

Without it, we can't use this plugin to ship data to our Kafka instance.

**Comment by repeatedly** [comment]
One developer is now trying to add kerberos support to ruby-kafka.
After that, I will add its feature to this plugin.

**Comment by tmeinlschmidt** [comment]
Added some preliminary support for SASL/GSSAPI authentication I created in ruby-kafka - see https://github.com/zendesk/ruby-kafka/issues/119

**Comment by kenhys** [comment]
It was supported since v0.9.5.
