### ISSUE TITLE
How to add unix time for message from sdks?

### ISSUE THREAD

**Issue by chrislee87** [fluent/fluent-plugin-kafka#116]
For input types as tcp, udp, http or tail, parser and time_key can be used to add unix time for each message. However, parser can not be used with in_forward. How to add unix time for messages from forward data source. 
1. When sending msg using sdk, a timestamp is included, how can i fetch this timestamp ?
```
Event{tag=%s,timestamp=%d,data=%s}
```
2. Can i  dynamiclly add unix time according to the receive time of the message?

**Comment by repeatedly** [comment]
Your question is for fluent-plugin-kafka or in_forward?

**Comment by chrislee87** [comment]
**_in_forward_**.  I had found output_include_time can used in fluent-plugin-kafka to fetch the timestamp.
