### ISSUE TITLE
Failed to assign partitions to messages

### ISSUE THREAD

**Issue by hongxin001** [fluent/fluent-plugin-kafka#131]
> Send exception occurred: Failed to assign partitions to 12 messages
> initialized kafka producer: kafka
> emit transaction failed: error_class=Kafka::DeliveryFailed error="Failed to assign partitions to 12 messages" tag="docker.3a255dc8f24acc2443d6003a178694593a4d8cacc72c5a1b427ee94680245849.catalina"

this is configuration file:

![2017-05-28 7 57 40](https://cloud.githubusercontent.com/assets/3424112/26528497/f45d45b6-43df-11e7-9205-80f1b828974e.png)

**Comment by kanupriya15025** [comment]
@w821881341  Did you find a solution to this.. I am stuck on the same error for a week now.

**Comment by kenhys** [comment]
It seems similar to  #111

**Comment by kenhys** [comment]
duplicated.
