### ISSUE TITLE
does out_kafka support SASL/PLAIN  auth? 

### ISSUE THREAD

**Issue by jeremywu0127** [fluent/fluent-plugin-kafka#133]
Our `kafka` cluster use `SASL/PLAIN ` auth, the config looks like
```
KafkaServer {
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="myid"
        password="mypassword"
};
```
But I didn't find any auth parameters in `out_kafka`, so does `out_kafka` support this?

**Comment by repeatedly** [comment]
Not yet. See https://github.com/fluent/fluent-plugin-kafka/issues/115 and https://github.com/zendesk/ruby-kafka/issues/119

**Comment by martinhynar** [comment]
Hi @repeatedly 
Would it be possible to add SASL/PLAIN? It is done in ruby-kafka now.

**Comment by roche-d** [comment]
Hi @repeatedly 

Is is possible to reopen the issue and provide support for SASL/PLAIN and SASL/SCRAM ?
From what I can see it seems to be supported in ruby-kafka (ref https://github.com/zendesk/ruby-kafka#authentication-using-sasl)

It would be greatly appreciated !

Thanks

**Comment by tomiloza** [comment]
Would be great if you can reopen this issue, we also need support for SASL/PLAIN authentication.

**Comment by vishalmamidi** [comment]
@repeatedly  Hi, it would be great if you can reopen this issue, we also need support for SASL/PLAIN authentication.
