### ISSUE TITLE
Byte Array type for kafka

### ISSUE THREAD

**Issue by maheshb415** [fluent/fluent-plugin-kafka#141]
Hi,

My Kafka topic stores records of type ByteArray. How can you use fluent-plugin-kafka to output byte array objects to a kafka topic?

Your help is highly appreciated.

Thanks
Mahesh

**Comment by repeatedly** [comment]
What does ByteArray mean?
If you post a question, please write detailed information together.

**Comment by repeatedly** [comment]
No response
