### ISSUE TITLE
suspending offset autocommit

### ISSUE THREAD

**Issue by vixns** [fluent/fluent-plugin-kafka#143]
I'm using this plugin to consume a kafka topic, then I'm applying some filters and send formated data to elasticsearch.

When elasticsearch has troubles, messages are not fully processed, but, as the kafka_group read was successfull, the offset is commited.

If is it possible, how can I detect the elasticsearch output plugin is stalled, and stop commiting offsets to the kafka group ?

**Comment by langzi-zmg** [comment]
In the configuration process, you have such a problem?
2017-08-07 18:58:38 +0800 [error]: #0 fluent/log.rb:356:error: unexpected error during consuming events from kafka. Re-fetch events. error="Unknown error with code 23"
2017-08-07 18:58:38 +0800 [error]: #0 fluent/log.rb:356:error: unexpected error during consumer object access error="undefined method `[]' for nil:NilClass"

**Comment by vixns** [comment]
No, consuming works, what's missing is a way to commit only when the message is fully processed by the output plugins.

**Comment by repeatedly** [comment]
> If is it possible, how can I detect the elasticsearch output plugin is stalled, and stop commiting offsets to the kafka group ?

Use out_kafka instead of out_kafka_buffered. The demerit is low performance.
out_kafka_buffered uses buffers and this has a merit that input plugin doesn't need to care output plugin temporarily errors.
Fluentd's buffered output retries buffer flush after elasticsearch is recovered.

**Comment by vixns** [comment]
kafka_group is the input, elasticsearch the output. I would like to commit the kafka offset only when the elasticsearch output plugin has successfuly sent the message.

**Comment by repeatedly** [comment]
Ah, sorry. I mixed other case.

> the elasticsearch output plugin has successfuly sent the message.

Currently no way because elasticsearch plugin is buffered output. So input and output are de-coupled.

**Comment by repeatedly** [comment]
If you want to do it, need to write non-buffered elasticsearch plugin.

**Comment by ncepuwanghui** [comment]
I encountered the same problem. I'm using this plugin to consume a kafka topic, then send the data to file, but lost some message.
