### ISSUE TITLE
source kafka_group, match hdfs ,but  get error.........

### ISSUE THREAD

**Issue by zzmg** [fluent/fluent-plugin-kafka#144]
error log:

2017-08-07 18:58:38 +0800 [error]: #0 fluent/log.rb:356:error: unexpected error during consuming events from kafka. Re-fetch events. error="Unknown error with code 23"
2017-08-07 18:58:38 +0800 [error]: #0 fluent/log.rb:356:error: unexpected error during consumer object access error="undefined method `[]' for nil:NilClass"
this is my configuration:
<source>
  @type kafka_group
  brokers 10.1.0.30:9092,10.1.0.106:9092,10.1.0.127:9092
  consumer_group accesslog2es
  topics user_activity
  format json
  use_record_time true
  max_bytes 1048576
  start_from_beginning false
  session_timeout 1000
  add_prefix webaccess
</source>

<match webaccess.**>
  @type  webhdfs
  buffer_type memory
  buffer_chunk_limit 256m
  buffer_queue_limit 128
  time_slice_format %Y%m%d%H
  path  /fluentd/ivanka/gateway/%Y/%m-%d/%H/webaccess.log
  <format>
    @type json
  </format>
  num_threads 10
  namenode  cdh5node4:50070
  standby_namenode  cdh5node3:50070
  flush_interval 10s
</match>

If I do not add add_prefix, the log will be passed to hdfs, but fluentd own log

who can help me????

**Comment by langzi-zmg** [comment]
Who can help me？？？？？

**Comment by repeatedly** [comment]
Could you show me stacktrace of errors?
