### ISSUE TITLE
Tag is getting replaced by the topic name

### ISSUE THREAD

**Issue by Kumaravel2904** [fluent/fluent-plugin-kafka#146]
I am using this plugin to send data from Fluent_Client to kafka and then retrieve the same data using Fluent_Server. The tag which I use in the client is overridden with the topic name.
Architecture 
Fluent --> Kafka --> Fluent
Is there a way to maintain the tag name while receiving the data in the Fluent_Server?

**Comment by agup006** [comment]
@Kumaravel2904 the default behavior when outputting is tag -> topic and then using the input plugin is topic -> tag. Code for tag can be seen in in_kafka.rb, and out_kafka.rb. For assistance in implementation or support see [enterprise support](https://fluentd.treasuredata.com/apache-kafka/)
