### ISSUE TITLE
Support timestamp in the Kafka protocol

### ISSUE THREAD

**Issue by kiyoto** [fluent/fluent-plugin-kafka#148]
Once ruby-kafka v0.5.0 becomes stable, we should upgrade. Here's the message I get when I run a KSQL query against the data streamed in by fluent-plugin-kafka

>Input record ConsumerRecord(topic = fluentd.host_001, partition = 0, offset = 1, CreateTime = -1, serialized key size = -1, serialized value size = 36, headers = RecordHeaders(headers = [], isReadOnly = false), key = null, value = [ ‘data into host_001.log’ ]) has invalid (negative) timestamp. Possibly because a pre-0.10 producer client was used to write this record to Kafka without embedding a timestamp, or because the input topic was created before upgrading the Kafka cluster to 0.10+. Use a different TimestampExtractor to process this data.

**Comment by kiyoto** [comment]
c.f.: https://github.com/fluent/fluent-plugin-kafka/issues/106

**Comment by repeatedly** [comment]
duplicated
