### ISSUE TITLE
http url in kafka brokers

### ISSUE THREAD

**Issue by inkitm** [fluent/fluent-plugin-kafka#152]
I am putting the Openshift Pod route in the kafka brokers field, but seems it is not accepting it,

<source>
@type kafka
brokers http://broker-myproject.172.1.11.43.oic.io:80
topics testtopic
</source>

The http address is directly mapped to broker port 9092 hence using the default port 80 for it.

But it Throws the following error,

[error]: Could not connect to any of the seed brokers:
- http://broker-myproject.172.1.11.43.oic.io: Connection error: EOFError

Any Ideas? Does it accept http address of the host.

**Comment by repeatedly** [comment]
We use ruby-kafka for connection.
Please test ruby-kafka without fluent-plugin-kafka and if it doesn't work, please open an issue on ruby-kafka.
