### ISSUE TITLE
ArgumentError: invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by Jonathan-mura** [fluent/fluent-plugin-kafka#153]
If there is an invalid byte  sequence in UTF-8 when using kafka-out, the log is lost

```
 unexpected error during format record. Skip broken event: error="invalid byte sequence in UTF-8" error_class="ArgumentError" 
```
It may be better to replace invalid byte  sequence with "?" using string-scrub

**Comment by repeatedly** [comment]
It is one idea but we need to iterate all fields to find the problematic field in the record.
So adding option is better.

**Comment by nderzhak** [comment]
What option ?
