### ISSUE TITLE
async_producer

### ISSUE THREAD

**Issue by gyustorm** [fluent/fluent-plugin-kafka#154]
Hi, may i ask that why we don't choose 'async_producer' here?
https://github.com/fluent/fluent-plugin-kafka/blob/a46d7794083113f6571cd6d320461da88c8e63c5/lib/fluent/plugin/out_kafka_buffered.rb#L212
![image](https://user-images.githubusercontent.com/16568915/31545795-61f984b0-b053-11e7-9599-957e13b28352.png)

kafka cluster info as follow:
100 brokers on 100 nodes,  1 disk per node;
topic_a 100 partition, 1 partition per node;
1 producer.

Imaging  a situation like this: 
Using one sync producer to send messages to every partition on every node;
Suddenly, one broker have a very high flush latency, messages sending to this broker are blocked. At the same time, messages sending to the other brokers are also blocked. 

sending messages to brokers in a loop without async:
https://github.com/zendesk/ruby-kafka/blob/v0.4.1/lib/kafka/produce_operation.rb#L81
![image](https://user-images.githubusercontent.com/16568915/31545849-8aab4574-b053-11e7-8c1c-895d7103c3df.png)

**Comment by repeatedly** [comment]
In fluentd, flush thread is separated from other threads.
So basic behaviour of buffered output is async.
If we use async_producer in kafka_buffered, it uses double threads for flush and it is not efficient.
In addition, async_producer stores logs in their memory queue.
It means if fluentd or machine is crashed during async write, logs are lost.
There is no merit in fluentd case.

**Comment by scharissis-wx** [comment]
Is this still the case in 2021?
https://github.com/fluent/fluent-plugin-kafka/blob/master/lib/fluent/plugin/out_kafka2.rb#L217 reads:
`# TODO: optimize write performance`
What is meant by that?

As a user of this library it's not clear to me if it's efficient, or even it it batches.

**Comment by repeatedly** [comment]
> What is meant by that?

We may improve the performance to remove several general code from `ruby-kafka`. The example is https://github.com/fluent/fluent-plugin-kafka/blob/master/lib/fluent/plugin/kafka_producer_ext.rb
But now, we provide rdkafka based output for more performance use-case. Maybe, we can remove this comment from the ruby-kafka based output.
