### ISSUE TITLE
kafka_group input not work

### ISSUE THREAD

**Issue by zhxiaom5** [fluent/fluent-plugin-kafka#156]
2017-10-28 16:57:15 +0800 [info]: plugin/in_kafka_group.rb:81:configure: Will watch for topics cdn_monitor at brokers es-kafka-server.cdn.gz4399.com:9092 and 'sbb' group
2017-10-28 16:57:15 +0800 [info]: fluent/engine.rb:133:configure: using configuration file: <ROOT>
``` 
 <source>
    @type kafka_group
    brokers es-kafka-server.com:9092
    topics cdn_monitor
    consumer_group sbb
    format text
    message_key myhaha
  </source>
  <match *.*>
    @type stdout
  </match>
```
</ROOT>

nothing output get，realy wired

**Comment by like-inspur** [comment]
I use newest version kafka as fluentd source. When I configure single consumer, it works. But when I configure consumer group, it output error：Connection error while trying to join group `fluentd`; retrying...
My config of single consumer and consumer group is same, I want to know why consumer group outputs errors. Thank you! @repeatedly @zhxiaom5 

Single consumer:
    <source>
      @type kafka
      brokers PLAINTEXT://kafka-0.kafka-svc:9093,PLAINTEXT://kafka-1.kafka-svc:9093,PLAINTEXT://kafka-2.kafka-svc:9093
      topics fluentd
    </source>
Consumer group:
    <source>
      @type kafka_group
      brokers PLAINTEXT://kafka-0.kafka-svc:9093,PLAINTEXT://kafka-1.kafka-svc:9093,PLAINTEXT://kafka-2.kafka-svc:9093
      consumer_group fluentd
      topics fluentd
    </source>

**Comment by repeatedly** [comment]
Maybe, the number of launched consumers is larger than your topic's partitions.

**Comment by like-inspur** [comment]
My topic's partitions number is 8, and consumers number is3. So it's not this reason.

**Comment by like-inspur** [comment]
how can I retain original tag from log when I use fluentd input kafka by consumer group method?
@zhxiaom5 @repeatedly @kataring @spiritloose
