### ISSUE TITLE
High CPU usage for 1000req/sec

### ISSUE THREAD

**Issue by GauravRai-GSLab** [fluent/fluent-plugin-kafka#16]
Hi,

Whenever I apply 1000req/sec load on fluentd with kafka buffered output plugin, my CPU usage goes beyond 90%, so is this a problem of poseidon(as it is implemented in pure ruby)?

Thanks,
Gaurav

**Comment by htgc** [comment]
Hello Gaurav,

It might be so, but you may be able to avoid this problem with Fluentd configuration.
Please let me know the value of "flush_interval" in your Fluentd configuration file.
If you don't set in the config file, Fluentd set 60 (seconds) as default. (i.e. send 60K messages at same
time).
Please try to set flush_interval to 5 to 10 (seconds) if you can.

Thanks,

**Comment by GauravRai-GSLab** [comment]
I tried all combination of flush interval from 1sec to 25sec but cpu usage remained same ie above 90%. for non buffered kafka plugin cpu usage remains around 72%.

**Comment by htgc** [comment]
Sure, so please let me know how large your message.
I'll try as same size as your environment.

**Comment by GauravRai-GSLab** [comment]
I have uploaded my log generator script, sample log file and fluentd configuration file on google drive 
https://drive.google.com/folderview?id=0Bxg6qMGV88wifnFheTh1TE0tLUNYN1JNQ3hRbVUweXY2OEM1eWFkd1drbXl5N1pfMTdjN1k&usp=sharing

In addition to kafka, I tried elasticsearch plugin which took 42% of cpu usage.

**Comment by htgc** [comment]
Sorry for late reply.
I tested your program on my local environment CPU usage went over 90% (almost 100%) while flushing logs.
I want you try to tune up the parameter "kafka_agg_max_bytes" in your config file.
Its default value is 4096 (bytes), so buffered logs are spit under 4096 bytes and send them, but it might be stacked in your environment.
I tried 40960 (40KB), CPU usage went up to 90% ( peak: around 85%, normally 45% ).

See more description of this parameter at following pull request.
https://github.com/htgc/fluent-plugin-kafka/pull/9

Thanks,

**Comment by phstudy** [comment]
I also have this problem...

**Comment by htgc** [comment]
@phstudy Thank you for your information. please let me know more details about your environment.

**Comment by phstudy** [comment]
@htgc It only happens when there are lots of remaining messages. So I think it can be ignored in my use case. Thanks!!

**Comment by htgc** [comment]
@phstudy Got it. Thanks!
