### ISSUE TITLE
Kafka message key is being ignored

### ISSUE THREAD

**Issue by javier-sanz** [fluent/fluent-plugin-kafka#160]
A Kafka message is a key value pair. But in the plugin the key cannot be extracted, or at least I was not able to do it. I had a look to the code I don't think that field on the message (field `key`, [see](https://github.com/zendesk/ruby-kafka#consuming-messages-from-kafka)) is being used at all. I initially though it was the `message_key` configuration value but that is a different thing. Could the Kafka message key be published somehow?

**Comment by repeatedly** [comment]
For support it, adding new parameter, e.g. `kafka_message_key`, is better.

**Comment by javier-sanz** [comment]
Thanks for your answer @repeatedly. Yes something like that would be great. I have no idea about Ruby so I cannot do the changes myself.
