### ISSUE TITLE
Dynamic topic support

### ISSUE THREAD

**Issue by nhamlh** [fluent/fluent-plugin-kafka#173]
I wonder if kafka plugin could support pushing messages to topics based on a field of the messages. For instance I'm pushing logs of docker container running on kubernetes cluster. I just want logs to be split by kubernetes namespace:

```yaml
<match kubernetes.**>
@type kafka
default_topic ${record['namespace_name']}
</match>
```

**Comment by nhamlh** [comment]
It's embarrassing that I dug into the code a bit after creating this issue and found out that we could set the topic of message by creating `topic` field.

**Comment by zzswang** [comment]
@nhamlh 

so do you mean, if we have log like:

```
{ topic: "some_namespace", message: "dsdfsdf" }
```

this log will send to kafka with topic==some_namespace ?

**Comment by Taymindis** [comment]
@zzswang 

you can have 
```
topic $.your_json_key
```
