### ISSUE TITLE
kafka://172.16.6.12:9092: Connection error EOFError: EOFError

### ISSUE THREAD

**Issue by matiji66** [fluent/fluent-plugin-kafka#177]
I, [2018-01-30T10:11:48.717181 #21020]  INFO -- : Fetching cluster metadata from kafka://172.16.6.11:9092
D, [2018-01-30T10:11:48.717181 #21020] DEBUG -- : Opening connection to 172.16.6.11:9092 with client id simple-producer...
D, [2018-01-30T10:11:48.764088 #21020] DEBUG -- : Sending topic_metadata API request 1 to 172.16.6.11:9092
D, [2018-01-30T10:11:48.764088 #21020] DEBUG -- : Waiting for response 1 from 172.16.6.11:9092
D, [2018-01-30T10:11:48.810940 #21020] DEBUG -- : Closing socket to 172.16.6.11:9092
D, [2018-01-30T10:11:48.810940 #21020] DEBUG -- : Closing socket to 172.16.6.11:9092
E, [2018-01-30T10:11:48.810940 #21020] ERROR -- : Failed to fetch metadata from kafka://172.16.6.11:9092: Connection error EOFError: EOFError

C:/Users/Downloads/ruby-kafka-master/lib/kafka/producer.rb:299:in `rescue in block in deliver_messages_with_retries': Could not connect to any of the seed brokers: (Kafka::DeliveryFailed)
- kafka://172.16.6.13:9092: Connection error EOFError: EOFError
- kafka://172.16.6.11:9092: Connection error EOFError: EOFError
- kafka://172.16.6.12:9092: Connection error EOFError: EOFError

**Comment by repeatedly** [comment]
Hmm... could you test ruby-kafka directly instead of fluent-plugin-kafka?
The error happens inside ruby-kafka - kafka communication.

**Comment by matiji66** [comment]
Yes ruby-kafka  does not support kafka 0.9.0.1 after 0.4.4 version,but ruby-kafka 0.4.4 will be ok.

**Comment by repeatedly** [comment]
> C:/Users/Downloads/ruby-kafka-master/lib/kafka/producer.rb:299:in `rescue in block in deliver_messages_with_retries': Could not connect to any of the seed brokers: (Kafka::DeliveryFailed)

From your log, you seems to use master. Is this 0.4.4?

**Comment by matiji66** [comment]
I have cloned the ruby-kafka of different version from 0.4.4 to master and debuged them in ruby ide to consume topic from kafka. Only 0.4.4 version passed the test. The error log was created from ruby master version,the other version which higher then 0.4.4 had similar errors！
And the errors look like that request protocols are not compatible in different ruby kafka.

**Comment by matiji66** [comment]
I should open issue in ruby kafka not this project after the test.

**Comment by abhinaya04** [comment]
I am getting the below error 
r_class=Kafka::ConnectionError error="Could not connect to any of the seed brokers:\n- kafka://172.31.7.133:2181: Connection error: EOFError"

Can u please help me in resolving the issue?

**Comment by yybear** [comment]
i got the erro too: 
2018-04-11 09:27:48 +0000 [warn]: #0 Send exception occurred: Could not connect to any of the seed brokers:
- kafka://kafkasit02broker01.cnsuning.com:9092: Connection error EOFError: EOFError
2018-04-11 09:27:48 +0000 [warn]: #0 Exception Backtrace : /usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/cluster.rb:292:in `fetch_cluster_info'
/usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/cluster.rb:252:in `cluster_info'
/usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/cluster.rb:82:in `refresh_metadata!'
/usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/cluster.rb:48:in `add_target_topics'
/usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/producer.rb:279:in `deliver_messages_with_retries'
/usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/producer.rb:241:in `block in deliver_messages'
/usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/instrumenter.rb:21:in `instrument'
/usr/lib/ruby/gems/2.3.0/gems/ruby-kafka-0.5.2/lib/kafka/producer.rb:234:in `deliver_messages'
/usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-kafka-0.6.6/lib/fluent/plugin/out_kafka_buffered.rb:267:in `deliver_messages'
/usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-kafka-0.6.6/lib/fluent/plugin/out_kafka_buffered.rb:316:in `block in write'
/usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/event.rb:323:in `each'
/usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/event.rb:323:in `block in each'
/usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/buffer/memory_chunk.rb:80:in `open'
/usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/buffer/memory_chunk.rb:80:in `open'
/usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/event.rb:322:in `each'
/usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-kafka-0.6.6/lib/fluent/plugin/out_kafka_buffered.rb:284:in `write'
/usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/compat/output.rb:131:in `write'
/usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:1093:in `try_flush'
/usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:1318:in `flush_thread_run'
/usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin/output.rb:439:in `block (2 levels) in start'
/usr/lib/ruby/gems/2.3.0/gems/fluentd-1.0.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2018-04-11 09:27:48 +0000 [info]: #0 initialized kafka producer: kafka
2018-04-11 09:27:48 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 next_retry_seconds=2018-04-11 09:27:49 +0000 chunk="5698f3cf35c507977e76f14aa5832c3f" error_class=Kafka::ConnectionError error="Could not connect to any of the seed brokers:\n- kafka://kafkasit02broker01.cnsuning.com:9092: Connection error EOFError: EOFError"

**Comment by tracers2222** [comment]
@matiji66, when you tested successfully with ruby-kafka 0.4.4, which version of fluent-plugin-kafka were you using? We have a need to connect to Kafka 2.0 using GSSAPI.
