### ISSUE TITLE
Events in Kafka partitions not consumed properly

### ISSUE THREAD

**Issue by zs787** [fluent/fluent-plugin-kafka#185]
Hi,

I am using the Kafka consumer group option and one problem I have is that few partitions out of the 50 have a very large consumer offset lag, that is never going down. The rest of the partitions seems to be fairly consumed but only few are left with a big lag. Example in the below screenshot.

![image](https://user-images.githubusercontent.com/34486307/36992898-4db19582-207a-11e8-8bb0-2cb7c488222b.png)

I have Logstash subscribed to the same topic and it never had this issue as I was able to control the number of threads, to at least match number of partitions. Not sure if this could be a timeout issue that somehow its taking time to be able to get to those partitions and thus Kafka keeps resetting the offset, to an older one ?  

BTW I have monitored the logs for some time and I see no issues indicating anything related to this.

**Comment by zs787** [comment]
I was able to overcome this issue by changing it to read from the latest (`start_from_beginning false`). I know since there is a checkpoint this should have no effect but still my theory is it looks like the offset/checkpoint was not committed on time and kept re-sending and resetting, as my lag wont go down for many of those partitions.
Which means under great pressure from Kafka looks like there were no enough threads to cover all of my 50 partitions.

**Comment by simonasr** [comment]
Hi, we are having exactly same issue.
We have a topic with 24 partitions, 3x td-agent machines with 8xCpu cores ant multiprocess enabled. Machines are under-utilised - ~20-30% CPU used, system load <3.

Some of the partitions have very large consumer offset lag and it keeps growing..
![image](https://user-images.githubusercontent.com/7496885/67206025-89840080-f419-11e9-964c-ed7cf0fb94f8.png)
Unfortunately setting `start_from_beginning` to `false` did not help :(
