### ISSUE TITLE
get_kafka_client_log has no effect

### ISSUE THREAD

**Issue by andlaz** [fluent/fluent-plugin-kafka#186]
i'm trying to debug a connection issue with `type: kafka_buffered`. I have `get_kafka_client_log` set to true in configuration, but i can see no additional kafka client log lines in fluentd logs..

is logger not passed in to Kafka.new? am i reading this right?

https://github.com/fluent/fluent-plugin-kafka/blob/a1260382343d1c397e7704619de01142f1fbd36b/lib/fluent/plugin/out_kafka_buffered.rb#L121

https://github.com/zendesk/ruby-kafka#logging

**Comment by repeatedly** [comment]
Thx for the report. This is the regression. Patch is here: https://github.com/fluent/fluent-plugin-kafka/pull/187

**Comment by repeatedly** [comment]
Release v0.7.2.
