### ISSUE TITLE
Add support for ssl_ca_certs_from_system

### ISSUE THREAD

**Issue by rchady** [fluent/fluent-plugin-kafka#189]
The ruby-kafka library has support for a parameter of ssl_ca_certs_from_system.  It is a boolean and if set to true it has it do what it says, use the system ca certs.  Without this, fluent-plugin-kafka can't really support connecting to the Confluent Cloud, for example.

To test it out, I passed it in to the Kafka.new() call.  Initially it failed because the ruby-kafka gem was not new enough, but after updating to the latest version it works as expected and I'm able to send messages.

Can this get added please?

**Comment by danmx** [comment]
@rchady `ssl_ca_certs_from_system` option is in the `master` branch so I think this issue can be closed :)

**Comment by cosmo0920** [comment]
Yep, we can close this issue.
Thank you!
