### ISSUE TITLE
plugin puts duplicate messages in kafka topic

### ISSUE THREAD

**Issue by piavlo** [fluent/fluent-plugin-kafka#19]
The plugin puts duplicate messages into kafka for some percentage of the messages.
Both for buffered and unbuffered outputs( thought with buffered output is seems the duplicates rate is lower).
The input comes from tail plugin.
It was verified that tailed files have no duplicates.
I also tried to put events both to kafka and local files with http://docs.fluentd.org/articles/out_copy
one store to kafka other with http://docs.fluentd.org/articles/out_file
the files written by out_file does not have any duplicates while kafka topic does.

This happens also with increasing  ack_timeout_ms and even with required_acks off.
Also with max_send_retries set to zero.

**Comment by htgc** [comment]
@piavlo Did you get any logs about this plugin when it happened? e.g. connection error, sending error etc..
I guess any error happened then retried by fluentd.(not poseidon)

Thanks,

**Comment by repeatedly** [comment]
No response.
