### ISSUE TITLE
When Fluentd is started, some messages consumed from Kafka get lost

### ISSUE THREAD

**Issue by pkout** [fluent/fluent-plugin-kafka#190]
We are using the following configuration of the input Fluentd Kafka plugin to send messages from Kafka to Elasticsearch:

```
<source>
  @type kafka
  brokers <ip_address>:9092
  topics topic1,topic2,topic3
</source>

<filter **>
  @type stdout
</filter>

<filter topic1>
  @type record_transformer
  enable_ruby
  <record>
    data ${record["data"].merge(:userId => record["data"]["userUrl"].split('/').pop())}
  </record>
</filter>

<match topic1>
  @type elasticsearch
  host <host>
  port 9243
  user elastic
  password <pwd>
  scheme https
  type_name log
  logstash_format true
  logstash_prefix topic1
</match>
```

I reducted the sensitive information, but this is the configuration. When we start up Fluentd with this configuration, some of the initial Kafka topic messages don't get captured by Fluentd. It seems to stabilize later on. Any ideas why this is happening? It renders the plugin unusable to us. 

The reason why we know that the problem is not with the Elasticsearch plugin is because some of the initial messages don't even get printed out the the standard output by the `stdout` plugin. I should also mention that we are running Fluentd 1.1 in a Docker container.

Thank you!

**Comment by danmx** [comment]
@pkout did you solve it?

**Comment by pkout** [comment]
@danmx Unfortunately not. We ended up writing our own Java program that sent data from Kafka to Elasticsearch.

**Comment by danmx** [comment]
Did you use multiple consumers with the same configuration? I’ve misconfigurated 2 consumers to ran with a single consumer configuration (`@type kafka`) and also noticed message loss and duplication. Changing to multiconsumer configuration (`@type kafka_group`) and setting the same consumer group fixed the issue.

**Comment by pkout** [comment]
Unfortunately, I don't where at that company anymore, so I don't have access to the code base to check. Thanks for posting your solution here, though. It can help others and me in the future.
