### ISSUE TITLE
delivery_interval option to ruby-kafka and generic ruby-kafka config

### ISSUE THREAD

**Issue by brettrann** [fluent/fluent-plugin-kafka#191]
ruby-kafka's delivery_interval is analogous to linger.ms in the official java clients, which allows forcing the client to wait until either the time has passed or the buffer is full before sending the message batch to kafka brokers.  This is a powerful setting when using compression since it's the message batch that gets compressed and compression works better with larger payloads.  It essentially trades a little latency for more throughput and less traffic and less storage requirements which is perfect for a logging pipeline.

It's probably worth also allowing any ruby-kafka config to be specified and generically passed through to the client, rather than wrapping each config in the plugin.

Thoughts on implementing this welcome.

**Comment by repeatedly** [comment]
> It's probably worth also allowing any ruby-kafka config to be specified and generically passed through to the client, rather than wrapping each config in the plugin.

This seems good idea. Using `:hash` type in `config_param` is for it.

```
config_param :kafka_client_options, :hash, :default => {}
```
