### ISSUE TITLE
MounthPath not getting the files if I will created a new file in the underlying mapped hostPath

### ISSUE THREAD

**Issue by AkshayDubey29** [fluent/fluent-plugin-kafka#197]
Hi We are running fluentd in kubernetes and facing an issue we are writing our log file to the underlying host path and we have mapped the same hostpath to the containers, once the container is getting restarted it will read all the existing files but will not read the latest files added to the path.

{
            "name": "log-dir",
            "hostPath": {
              "path": "/applog/container/logs/"
            }

{
                "name": "log-dir",
                "mountPath": "/applog/container/logs/"
              },

**Comment by repeatedly** [comment]
This seems to not kafka plugin issue.
