### ISSUE TITLE
Support exactly once delivery

### ISSUE THREAD

**Issue by jaynblue** [fluent/fluent-plugin-kafka#219]
Recently, Ruby-Kafa support Exactly-Once delivery feature.
(https://github.com/zendesk/ruby-kafka/pull/608)

We have to implement this great feature.

```
producer = kafka.producer(idempotent: true)
producer.produce('Testing', topic: 'test')
producer.deliver_messages

producer = kafka.async_producer(idempotent: true)
producer.produce('Testing 2', topic: 'test')
```

Thanks!

**Comment by repeatedly** [comment]
v0.8.0 uses ruby-kafka v0.7 or later so adding parameter for `idempotent` seems to resolve this problem.
