### ISSUE TITLE
Echarts 结合百度地图 绘制散点图 缩放过程中点名字错位问题

### ISSUE THREAD

**Issue by xingyunhui** [fluent/fluent-plugin-kafka#235]
使用echarts结合百度地图绘制了一个散点图，数据量大概几千，在缩放的过程中，有部分点的名字label出现的错位，显示的不是当前点的名字，鼠标选中触发选中效果后，就可正常显示，有大神遇到过这种问题么

**Comment by kenhys** [comment]
It has nothing to do with.
