### ISSUE TITLE
Specify ALL brokers

### ISSUE THREAD

**Issue by chrisdebug** [fluent/fluent-plugin-kafka#245]
I was planning to put a load balancer (with ssl) in front of a Kafka cluster so I can add and remove brokers from the cluster as necessary.

The fluentd broker config option says:
```
brokers (required/optional)
The list of all seed brokers, with their host and port information.
```
Is *list of all seed brokers* necessary? I was hoping to only specify the URL to the load balancer. I can't afford to constantly change the broker setting for all my servers every time I add and remove Kafka brokers.

**Comment by repeatedly** [comment]
> Is _list of all seed brokers_ necessary?

If your load blancer doesn't change any protocol between fluentd and broker, it should work.
fluent-plugin-kafka uses https://github.com/zendesk/ruby-kafka internally, so you can check the behaviour on your side.
