### ISSUE TITLE
How to set up kerberos authentication using fluent-plugin-kafka? 

### ISSUE THREAD

**Issue by NidhiArien** [fluent/fluent-plugin-kafka#253]
HI, 

We are using Fluent D to send data to Kafka using fluent-plugin-kafka. However our in house Kafka only accepts Kerberos authentication. In logstash, syslog-Ng we could set up Kerberos authentication using krb5.conf in JAVA_OPTS. I am not sure how to proceed with this plugin as the example code only talks about sasl_gssapi_principal and keytab: https://github.com/zendesk/ruby-kafka#authentication-using-sasl. We would need additional parameters like "Djava.security.krb5.conf"  Any advise? 

Thanks

**Comment by repeatedly** [comment]
Yes. Here is supported parameters for ruby-kafka: https://github.com/fluent/fluent-plugin-kafka#sasl-authentication

**Comment by NidhiArien** [comment]
> Yes. Here is supported parameters for ruby-kafka: https://github.com/fluent/fluent-plugin-kafka#sasl-authentication

Thank you. That link also only talk about two parameters: principal and keytab. How do I go about configuring other parameters for Kerberos authentication? We would need additional parameters as shown below

```
sasl.kerberos.service.name=kafka
security.protocol=SASL_PLAINTEXT
client.id=
sasl.mechanism=GSSAPI
sasl.jaas.config=
```

**Comment by AdimUser** [comment]
@repeatedly , @NidhiArien  +1 
That is good suggestion, because our logs are transfer within internal networks & not sending sensitive  data. hence It is good to have the support for SASL for plain text

**Comment by GokcerBelgusen** [comment]
Hi, is there any progress on  Kerberos authentication ?

**Comment by repeatedly** [comment]
What does `any progress` mean?
kakfa output plugins support kerberos. 
If `out_kafka2` doesn't work, `out_rdkafka2` may work.

**Comment by vezir** [comment]
In an environment of cloudera 6.3 with Kerberos authentication (GSSAPI), fluentd v1.9.2 plugin fluent-plugin-kafka, out_kafka2 did not work. I tried rdkafka2 with the advice of @repeatedly and it works now.

Details;

principal and keytab same as kafka2

parameters specific to rdkafka2
service_name  'kafka'

you can check [the code](https://github.com/fluent/fluent-plugin-kafka/blob/master/lib/fluent/plugin/out_rdkafka2.rb), as it fills all the necessary parameters for GSSAPI, SASL_PAINTEXT scenario mentioned by @NidhiArien 
 
`      if @principal
        sasl = true
        config[:"sasl.mechanisms"] = "GSSAPI"
        config[:"sasl.kerberos.principal"] = @principal
        config[:"sasl.kerberos.service.name"] = @service_name if @service_name
        config[:"sasl.kerberos.keytab"] = @keytab if @keytab
      end

      if ssl && sasl
        security_protocol = "SASL_SSL"
      elsif ssl && !sasl
        security_protocol = "SSL"
      elsif !ssl && sasl
        security_protocol = "SASL_PLAINTEXT"
      else
        security_protocol = "PLAINTEXT"
      end
      config[:"security.protocol"] = security_protocol`

Added to this, do not forget to add environment variable -Djava.security.auth.login.config=/home/user/jaas.conf
for details of jaas conf  this [link](https://docs.cloudera.com/runtime/7.1.0/kafka-securing/topics/kafka-secure-kerberos-enable.html).

Thank you @repeatedly

**Comment by CharlKlein** [comment]
Is there the Ability to set the _sasl.mechanisms_ to PLAIN ?

**Comment by hasmizal** [comment]
I have similar issue as the original question, is there a way to specify customize kerberos krb5.conf when running fluentd instead of using the default /etc/krb5.conf.
