### ISSUE TITLE
Recent change to ruby-kafka library breaks fluent-plugin-kafka

### ISSUE THREAD

**Issue by rchady** [fluent/fluent-plugin-kafka#260]
Just installed td-agent on a new system and it installed version 0.7.7 of the ruby-kafka plugin.  This breaks fluent-plugin-kafka with the following error:

2019-05-21 09:58:06 -0400 [error]: unexpected error error_class=NoMethodError error=#<NoMethodError: undefined method `verify_hostname=' for #<OpenSSL::SSL::SSLContext:0x007f27a066b3f8>>

This is from a recent merge that tries to use the verify_hostname= method of openssl that was added 3 years ago.  My guess is you need to specify a requirement for a newer version of openssl.

**Comment by kenhys** [comment]
verify_hostname was supported since ruby-kafka 1.1.0.
https://github.com/zendesk/ruby-kafka/blob/master/CHANGELOG.md#110

**Comment by kenhys** [comment]
Since ruby-kafka v0.7.9, the availability of `verify_hostname` is checked. so ruby-kafka v0.7.9 or later solves it.

https://github.com/zendesk/ruby-kafka/blob/master/CHANGELOG.md#079
