### ISSUE TITLE
why not support lz4 compression for kafka2

### ISSUE THREAD

**Issue by like-inspur** [fluent/fluent-plugin-kafka#266]
kafka support compression codecs  such as gzip, snappy and lz4. But this plugin only support gzip and snappy, I found that lz4 is better for use in many environments, why not suppoort lz4 for kafka2? Thank you!

**Comment by repeatedly** [comment]
Maybe, lz4 works.
First ruby-kafka doesn't support lz4 so it is missing from document.
Maybe link to ruby-kafka document is better for fixed values.

**Comment by repeatedly** [comment]
Outdated document is fixed in https://github.com/fluent/fluent-plugin-kafka/commit/accb14249b0ba8e495f967580fac7dd4cfd740df

**Comment by like-inspur** [comment]
thank you, I found using lz4 compression requires adding a dependency on the `extlz4` gem to your Gemfile. I will try it and help you make a supplement for document

**Comment by like-inspur** [comment]
hello，I create pull request, please agree it, thank you! @repeatedly
