### ISSUE TITLE
Unable to send message from fluentd to kafka

### ISSUE THREAD

**Issue by rameshVeeramani** [fluent/fluent-plugin-kafka#267]
I'm trying to setup a pipeline of data transfer  to Kafka through Fluentd . 
The topic do get created on kafka , but the messages are not been recorded
following are my td-agent.conf 

 I have Kafka version 2.0 (which according the ruby-kafka 0.7.8 has support) 

following are my td-agent.conf 

```<match **>
  @type kafka_buffered
  brokers <BrokerIP>:9092
  topic_key fluentdTopicKey
  default_topic fluentdDefaultTopic
  output_data_type json
  output_include_tag true
  output_include_time true
  get_kafka_client_log false
  required_acks 1
  compression_codec gzip
</match>
```
The td_agent.log has the following meesage
```
2019-06-04 15:12:25 -0500 [warn]: #0 Send exception occurred: Failed to send messages to fluentdDefaultTopic/0
2019-06-04 15:12:25 -0500 [warn]: #0 Exception Backtrace : /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.6/lib/kafka/producer.rb:414:in `deliver_messages_with_retries'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.6/lib/kafka/producer.rb:251:in `block in deliver_messages'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.6/lib/kafka/instrumenter.rb:23:in `instrument'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.6/lib/kafka/producer.rb:244:in `deliver_messages'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.9.4/lib/fluent/plugin/out_kafka_buffered.rb:286:in `deliver_messages'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.9.4/lib/fluent/plugin/out_kafka_buffered.rb:349:in `write'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/compat/output.rb:131:in `write'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:1125:in `try_flush'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:1425:in `flush_thread_run'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:454:in `block (2 levels) in start'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-06-04 15:12:25 -0500 [info]: #0 initialized kafka producer: kafka
2019-06-04 15:12:25 -0500 [warn]: #0 failed to flush the buffer. retry_time=9 next_retry_seconds=2019-06-04 15:16:58 -0500 chunk="58a8504d8f90f162cb010fe08de99d45" error_class=Kafka::DeliveryFailed error="Failed to send messages to fluentdDefaultTopic/0"
  2019-06-04 15:12:25 -0500 [warn]: #0 suppressed same stacktrace
```
Sorry if this a duplicate question ; would be helpfule if you direct me too
Thanks
Ram

**Comment by windgan** [comment]
@rameshVeeramani Have you fixed this problem? I have the same issue with **ruby-kafka-0.7.8**, **fluentd-1.6.1** and **fluent-plugin-kafka-0.10.0**

**Comment by repeatedly** [comment]
I tested the combination of latest ruby-kafka and kafka broker and it works on my local environment.
So if the error happens during sending events, the problem seems network or other settings.

### env

- kafka_2.12-2.3.0
- fluentd v1.6.0
- fluent-plugin-kafka 0.10.0
- ruby-kafka 0.7.8

### conf

```
<source>
  @type forward
</source>

<match test.**>
  @type kafka2  # use kafka2 for v1

  brokers localhost:9092
  default_topic test
  get_kafka_client_log true
  required_acks 1
  compression_codec gzip

  <format>
    @type json
  </format>
  <inject>
    tag_key tag
    time_key time
  </inject>
  <buffer tag> # need tag for tag_key
    flush_interval 5s
  </buffer>
</match>
```

### result

#### post test event

```
% echo '{"message":"hello"}' | fluent-cat test.foo
```

#### producer

```
% bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic test --from-beginning
{"message":"hello","tag":"test.foo","time":1562860532.839199}
```

**Comment by xidiandb** [comment]
I have the same problem,When I removed the buffer, it worked well again.Restart fluentd,the problem arises again. Does the problem have to do with rebooting fluentd or rebooting kafka?

**Comment by gangavarapusatwik** [comment]
> I tested the combination of latest ruby-kafka and kafka broker and it works on my local environment.
> So if the error happens during sending events, the problem seems network or other settings.
> ### env
> 
>     * kafka_2.12-2.3.0
> 
>     * fluentd v1.6.0
> 
>     * fluent-plugin-kafka 0.10.0
> 
>     * ruby-kafka 0.7.8
> 
> 
> ### conf
> 
> ```
> <source>
>   @type forward
> </source>
> 
> <match test.**>
>   @type kafka2  # use kafka2 for v1
> 
>   brokers localhost:9092
>   default_topic test
>   get_kafka_client_log true
>   required_acks 1
>   compression_codec gzip
> 
>   <format>
>     @type json
>   </format>
>   <inject>
>     tag_key tag
>     time_key time
>   </inject>
>   <buffer tag> # need tag for tag_key
>     flush_interval 5s
>   </buffer>
> </match>
> ```
> 
> ### result
> #### post test event
> 
> ```
> % echo '{"message":"hello"}' | fluent-cat test.foo
> ```
> 
> #### producer
> 
> ```
> % bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic test --from-beginning
> {"message":"hello","tag":"test.foo","time":1562860532.839199}
> ```

this configuration works thanks buddy
