### ISSUE TITLE
How to make consumer start consuming  from CURRENT-OFFSET after restarting consumer?

### ISSUE THREAD

**Issue by zkcarterlau** [fluent/fluent-plugin-kafka#285]
I used fluent-plugin-kafka to consume messages from kafka(kafka_2.11-2.2.0).When I  stopped the consumer the top lag was about 8000. Then I started the consumer to make it consume from kafka,I saw the lag turned to 0 immediately and I lost some messages.
    It seems like it starts consuming from LOG-END-OFFSET instead of CURRENT-OFFSET.It will cause messages missing when consumers are down.How can I make the consumer start consume from CURRENT-OFFSET after restarting?

**Comment by vikasmishra17** [comment]
Hi @zkcarterlau , How did you solved this problem?
