### ISSUE TITLE
how to support dynamic topic

### ISSUE THREAD

**Issue by foxracle** [fluent/fluent-plugin-kafka#286]
how to support dynamic topic, the config does not work. 

we get the error:
2019-08-14 17:38:59 +0800 [warn]: #0 [log_to_kafka] failed to flush the buffer. retry_time=11 next_retry_seconds=2019-08-14 17:55:47 +0800 chunk="59010464d29a13a4b908365ea2bbf8c0" error_class=Kafka::InvalidTopic error="Kafka::InvalidTopic"

>   @type kafka2
  brokers kafka-001
  default_topic ${tag}

**Comment by repeatedly** [comment]
No need because tag is used by default.

https://github.com/fluent/fluent-plugin-kafka/blob/master/lib/fluent/plugin/out_kafka2.rb#L218

**Comment by foxracle** [comment]
Thanks

**Comment by zoheb303** [comment]
What if i want something like date.
default_topic ${date}

**Comment by wangdexin0825** [comment]
如何使用fluentd输出到kafka时，不同的日志输出到对应不同的topic呢

**Comment by Taymindis** [comment]
@zoheb303 @wangdexin0825 

如果你的logs 是 { "message": "2022-06........ hello world", "topic": "topicA"}

那在kafka output 就會是“topicA”
