### ISSUE TITLE
function read_ssl_file doesn't support chained certificates

### ISSUE THREAD

**Issue by artur-fijalkowski** [fluent/fluent-plugin-kafka#287]
This is not mentioned explicitly in README.md, but read_ssl_file function doesn't support chained certificates. In *NIX environment this is very common that *.pem file contains multiple certificates concatenated together (eg. root CA + intermediate CA).

https://github.com/fluent/fluent-plugin-kafka/blob/d0d9bbf51c9e5b16c18379917b3603a256262429/lib/fluent/plugin/kafka_plugin_util.rb#L35

This is (most probably) easy to fix by splitting file during read on BEGIN CERTIFICATE line.

**Comment by repeatedly** [comment]
I'm not sure this sho uld be fixed in fluent-plugin-kafka or ruby-kafka.
Does this mean ruby-kafka supports chained certificates but fluent-plugin-kafka doesn't use it or ruby-kafka should accept chained certificates?

**Comment by artur-fijalkowski** [comment]
I think that because ruby-kafka expects to get array of certificates and actual file read is in fluent-plugin-kafka the plugin is proper place for implementation. Also current documentation is a bit misleading. As it doesn't say anything about lack of chaining support (neither that ssl_ca_cert is an array of files).

**Comment by syedriko** [comment]
There is a workaround: split the CA bundle file into individual PEM files and specify them as an array in fluent-plugin-kafka config:

ssl_ca_cert ["root_ca.crt", "intermediate_ca.crt"]

This takes advantage of https://github.com/fluent/fluent-plugin-kafka/blob/da73a50661c6e78f3e45f3e6aab535924aba9b09/lib/fluent/plugin/kafka_plugin_util.rb#L38

**Comment by syedriko** [comment]
I'm working on a proper fix.

**Comment by syedriko** [comment]
https://github.com/fluent/fluent-plugin-kafka/pull/390 is the PR tracking work on this issue, hopefully that'll un-stale it.

**Comment by ashie** [comment]
Fixed by #410
