### ISSUE TITLE
Issue for disconnect Kafka broker more frequently 

### ISSUE THREAD

**Issue by yichingwu** [fluent/fluent-plugin-kafka#290]
I am not friendly in Ruby, but I just want to confirm that I found Fluent-plugin-kafka disconnect every time once the messages were sent to Kafka. It will effect the performance issue if you always create a new connection to kafka for the new producer Object be created.

![image](https://user-images.githubusercontent.com/829351/64410859-87125500-d0be-11e9-9549-c8b9b7b10f64.png)

**Comment by repeatedly** [comment]
I assume this is `kafka2`, right?
Yeah, kafka2 now creates kakfa producer for each `write` call.
To avoid this issue, caching producer is better for thread/tag.

**Comment by yichingwu** [comment]
hi @repeatedly , yes your are right .
I use kafka2 and found out the source "out_kafka2.rb" as below.

![image](https://user-images.githubusercontent.com/829351/64423179-77076f00-d0d8-11e9-9183-e2cb6909228a.png)

**Comment by repeatedly** [comment]
I checked the performance of `producer.shutdown` but it is very low, e.g. elapsed time is `8.2e-05`.
So the performance problem happens in broker side?

**Comment by sreenuraghavan** [comment]
> I checked the performance of `producer.shutdown` but it is very low, e.g. elapsed time is `8.2e-05`.
> So the performance problem happens in broker side?

How do we cache the producer?

**Comment by sreenuraghavan** [comment]
> I assume this is `kafka2`, right?
> Yeah, kafka2 now creates kakfa producer for each `write` call.
> To avoid this issue, caching producer is better for thread/tag.

@repeatedly How do we cache the producer?

**Comment by yichingwu** [comment]
> I checked the performance of `producer.shutdown` but it is very low, e.g. elapsed time is `8.2e-05`.
> So the performance problem happens in broker side?

As I understood about Kafka cluster mechansim, I producer

**Comment by sreenuraghavan** [comment]
@yichingwu hello, did you find any fix for this?

**Comment by raytung** [comment]
Hey @repeatedly, I'd like to revive this thread if possible. While creating and shutting down connections have minimal impact to Fluentd's performance, but if we combine this behavior with `idempotent: true`, this can actually cause Kafka brokers to go OOM and crash during high load (~200,000 messages per second to Kafka). 

I'm happy to create a patch for this as well if that works better.

**Comment by raytung** [comment]
Created a patch for this https://github.com/fluent/fluent-plugin-kafka/pull/454 :bowing_man:
