### ISSUE TITLE
Fluentd to Kafka of speed is too slow

### ISSUE THREAD

**Issue by WangMingJue** [fluent/fluent-plugin-kafka#300]
I have two fluentd work:
1. fluentd to es
2. fluentd to kafka (According to the test, kakfa's producer speed is 200MB/s)
ps: Both fluentds were tested on the same Host

After test, result as follows:
1. fluentd to es:
    cpu up to 21%, mem up to 2.4%, send speed 20MB/s
2. fluentd to kafka:
    cpu up to 105%, mem up to 2.7%, send speed 6.7MB/s

Why is there so much difference between the two speed? Or, why is Fluentd sending to Kafka so slow? (regardless of the configuration of ES and Kafka, I have optimized it.)

I wonder if there is something wrong with my configuration? Or any other Suggestions.

fluentd_to_kafka.conf:
[1.txt](https://github.com/fluent/fluent-plugin-kafka/files/3878217/1.txt)

fluentd_to_es.conf:
[2.txt](https://github.com/fluent/fluent-plugin-kafka/files/3878219/2.txt)

**Comment by cosmo0920** [comment]
@WangMingJue fluent-plugin-elasticsearch's configuration is insufficient if your ES cluster is more capability.
`bulk_message_request_threshold -1` should improve ES benchmark performance:
https://github.com/uken/fluent-plugin-elasticsearch#bulk_message_request_threshold

**Comment by WangMingJue** [comment]
@cosmo0920 Thanks for your answer!
Maybe my question description is not accurate. What I want to ask is, why is the speed of my fluent sending to Kafka so low?

**Comment by cosmo0920** [comment]
Slow sending Kafka is well-known issue.

fluent-plugin-elasticsearch just dump Fluentd events as JSON: 

https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/out_elasticsearch.rb#L562-L585

fluent-plugin-kafka will encode Fluentd events with Kafka protocol:
https://github.com/fluent/fluent-plugin-kafka/blob/master/lib/fluent/plugin/out_kafka2.rb#L259

https://github.com/zendesk/ruby-kafka/blob/abf50eeff87d6499684c8222b346a9d6645adc3b/lib/kafka/protocol/message.rb#L145-L169

This encode process causes high CPU loading.

**Comment by WangMingJue** [comment]
@cosmo0920 Thank you for your answer!
In the process of my observation, I found my CPU usage was too high, but I can't found the reason.
I used a single thread to track my log file and send it to Kafka.
Is there any way to make it more efficient to track individual log files in a single thread?
Or has Fluentd reached the limit of single thread, no way to improve?(I've tried multithreading, but I'm only focusing on single-threaded use right now.)

**Comment by repeatedly** [comment]
How about using `rdkafka2`? It uses librdkafka internally: https://github.com/fluent/fluent-plugin-kafka#rdkafka-based-output-plugin

**Comment by WangMingJue** [comment]
@repeatedly Thank you very much!!!
I have been busy with other things recently, so I just conducted the test today.
Using rdkafka2 does provide a significant increase in delivery speed.
Of course, I haven't yet verified the consumption format in Kafka, but the speed of delivery has surprised me!
Thank you again!
