### ISSUE TITLE
Consumer plugins are unable to use Plain SASL authentication without SSL 

### ISSUE THREAD

**Issue by StevTheDev** [fluent/fluent-plugin-kafka#304]
The ruby-kafka docs say:

>NOTE: With SASL for authentication, it is highly recommended to use SSL encryption. The default behavior of ruby-kafka enforces you to use SSL and you need to configure SSL encryption by passing ssl_ca_cert or enabling ssl_ca_certs_from_system. However, this strict SSL mode check can be disabled by setting sasl_over_ssl to false while initializing the client.

Both in_kafka and in_kafka_group plugins provide the sasl_over_ssl configuration parameter, but this parameter is not referenced when creating a kafka object using the "plain" sasl authentication method.

I created a [PR here](https://github.com/fluent/fluent-plugin-kafka/pull/303) which would add this parameter to these calls in the in_kafka and in_kafka_group plugins.

**Comment by kenhys** [comment]
#303 was merged.
