### ISSUE TITLE
how can I use topic_key in Second-level dictionary

### ISSUE THREAD

**Issue by ZPerling** [fluent/fluent-plugin-kafka#306]
Now，my log example is
<pre>
{
   "message": "balabalabala",
    "kubernetes": {
      "container_name": "",
      "namespace_name": "social-stag",
      "pod_name": "social-feed-service-test-stag-747c78694c-mxjgz",
      "pod_id": "944ec07a-1d94-11ea-8b7d-525400d786a4",
      "host": "10.76.2.246",
      "labels": {
        "cluster": "stag",
        "cop": "abc",
        "owt": "social",
        "pdl": "social",
        "pod-template-hash": "747c78694c",
        "service": "social-feed-service-test",
        "servicegroup": "feed"
      }
}
</pre>

I want to use [kubernetes][labels][service] as my topic-key，how can i config?

**Comment by repeatedly** [comment]
How about putting `$.kubernetes.labels.service` into chunk keys and `topic` parameter?

**Comment by ZPerling** [comment]
Yes, using fluent-plugin-kubernetes_metadata_filter

**Comment by ZPerling** [comment]
> How about putting `$.kubernetes.labels.service` into chunk keys and `topic` parameter?

Yes, using fluent-plugin-kubernetes_metadata_filter

**Comment by holinnn** [comment]
I would need the same thing.
I would like to be able to send events to different topics based on annotations.

@repeatedly what do you mean by :

> How about putting $.kubernetes.labels.service into chunk keys and topic parameter?

**Comment by repeatedly** [comment]
> what do you mean by :

Which point is unclear?

**Comment by holinnn** [comment]
You seemed to give a hint on how to solve this problem.
I'm not a fluentd expert, so in fact I don't understand which configuration to change when you say `putting $.kubernetes.labels.service into chunk keys and topic parameter`

**Comment by repeatedly** [comment]
like below:

```
topic_key $.kubernetes.labels.service
<buffer $.kubernetes.labels.service>
  # ...
</buffer>
```
