### ISSUE TITLE
performance of kafka_buffered type

### ISSUE THREAD

**Issue by liyongxin** [fluent/fluent-plugin-kafka#309]
does anybody test the performance of kafka_buffered type???
I did a simple test，found It takes about 4~5 seconds to send 10m data，Send almost 10,000 data per second，i think the performance is poor, is it my configuration error or other reasons, can anyone tell??

my config file as below:
![image](https://user-images.githubusercontent.com/7601142/71716423-aa23fa00-2e4f-11ea-8241-7b5355e6e45b.png)

and this is the debug log

![image](https://user-images.githubusercontent.com/7601142/71716351-5ca78d00-2e4f-11ea-93aa-23ab61410d6f.png)

**Comment by liyongxin** [comment]
@repeatedly

**Comment by repeatedly** [comment]
> i think the performance is poor

You set `required_acks -1`, -1 is same with all, so kafka broker waits ack response until all replicas acknowledge.
If only fluent-plugin-kafka(ruby-kafka) takes longer time for this case, wait ack for all replicas with 10mb data, consider rdkafka version.
