### ISSUE TITLE
output_data_type json without escping

### ISSUE THREAD

**Issue by y0y0z** [fluent/fluent-plugin-kafka#318]
i am using version [0.12.3](https://github.com/fluent/fluent-plugin-kafka/releases/tag/v0.12.3).

i have an application which outputs its logs in json format, but my console consumer shows that the logs are escaped.

for instance, the application output the following log line:
```json
{"msg": "ok"}
```
when i look at the log using the console consumer, it outputs:
```json
{"container_id":"7e...","container_name":"/app","source":"stdout","log":"{\"msg\": \"ok\"}"}
```

how can i make sure that the application log will be nested as a json without escaping it?
thank you

**Comment by geeky-smurf** [comment]
i found the solution by using [record transformer filter](https://docs.fluentd.org/filter/record_transformer)

**Comment by y0y0z** [comment]
found a solution using [record transformer filter](https://docs.fluentd.org/filter/record_transformer)
