### ISSUE TITLE
kafka_group - SSLError - certificate verify failed 

### ISSUE THREAD

**Issue by mikolajmorawski** [fluent/fluent-plugin-kafka#325]
Hi, 
 Could you please verify the following issue. 

I think that in:
**in_kafka_group**.rb and  **in_kafka.rb**
 
is missing **ssl_verify_hostname: @ssl_verify_hostname parameter.** 

I am trying to use kafka_group to connect and consume logs from Kafka.

I am using the following versions:

fluent/fluentd:v1.9.2-debian-1.0
ruby-kafka-0.7.8
fluent-plugin-kafka -v 0.12.4
snappy:0.0.17
Kafka Server: kafka:2.12-2.2.0

config:

```
<source>
    @type kafka_group
    client_id local-fluentd
    brokers localhost:9094
    consumer_group group
    topics <topics names>
    ssl_ca_cert /fluentd/etc/caroot.pem - CA Root certificate ( from kafka )
    username admin
    password <password>
    disable_retry_limit true
    ssl_verify_hostname false - I thing this is not working, but required here. 
</source>
```

I am trying to use SASL_PLAIN over SSL to connect to Kafka. 

During connection to Kafka I am receiving the following execption:
`2020-03-03 20:09:25 +0000 [error]: #0 fluent/log.rb:362:error: unexpected error error_class=OpenSSL::SSL::SSLError error="SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error)"`

Kafka certificates are self-signed. 

Did you encounter a similar issue?
Do you think that this parameter is the root cause?

**Comment by mikolajmorawski** [comment]
update:
 This config is working with success with the following versions:
   ruby-kafka -v 0.7.5
   fluent-plugin-kafka -v 0.8.3

I am wondering why this is not working with the latest versions.

**Comment by mikolajmorawski** [comment]
Could you please verify the "kafka_group" missing parameters ? Did you encounter the similiar issue using "kafka_group" source ?

**Comment by repeatedly** [comment]
Patch: https://github.com/fluent/fluent-plugin-kafka/pull/351

**Comment by frankreno** [comment]
Note the PR That resolved this only resolved for the `kafka_group` input plugin.  I've submitted #368 to resolve this for the `kafka` input plugin.
