### ISSUE TITLE
What are the advantages of rdkafka over ruby-kafka

### ISSUE THREAD

**Issue by xidiandb** [fluent/fluent-plugin-kafka#331]
We want to know what the advantages of rdkafka , and why there is no plugin for consumers

**Comment by repeatedly** [comment]
> We want to know what the advantages of rdkafka

It may avoid ruby-kafka dependent issue.
In addition, rdkafka is basically faster than ruby-kafka.

> why there is no plugin for consumers

We introduced rdkafka output for expanding output use-case. If anyone has rdkafka's consumer knowledge, contribution is welcome :)

**Comment by kenhys** [comment]
https://github.com/fluent/fluent-plugin-kafka/issues/331#issuecomment-611890282 answers it.
