### ISSUE TITLE
Must fluentd's verison below 2?

### ISSUE THREAD

**Issue by ZhangSIming-blyq** [fluent/fluent-plugin-kafka#336]
![image](https://user-images.githubusercontent.com/58658883/82544257-725fe980-9b87-11ea-83cd-dffcec75e07e.png)

### I saw this picture, in my situation, fluentd version is v2.6.0

**Comment by ZhangSIming-blyq** [comment]
After install fluent-plugin-kafka by

**Comment by repeatedly** [comment]
latest fluentd version is v1.10.4, not 2.6.0. See https://rubygems.org/gems/fluentd

**Comment by repeatedly** [comment]
This seems prometheus-client version issue, not kafka plugin. Closed
