### ISSUE TITLE
Do message_key support something like "$.kubernetes.pod_name"?

### ISSUE THREAD

**Issue by ZhangSIming-blyq** [fluent/fluent-plugin-kafka#337]
The output in Kafka:
![image](https://user-images.githubusercontent.com/58658883/82653500-de0e8900-9c51-11ea-891d-ea7b4a0537b7.png)
This is obviously not what I want.
I know for topic_key it do support "$.kubernetes.pod_name", so, Do message_key support some exression like "$.kubernetes.pod_name"?

**Comment by repeatedly** [comment]
Hmm... currently, `message_key` and `partition_key` don't support record_accessor syntax.

**Comment by ZhangSIming-blyq** [comment]
> Hmm... currently, `message_key` and `partition_key` don't support record_accessor syntax.

Thanks, I see.

**Comment by ZhangSIming-blyq** [comment]
One more question, currently I use "topic_key            $.kubernetes.labels.release"
But I want "topic_key             FLUENTD-$.kubernetes.labels.release"

When I release this config,my fluentd failed with:
```shell
2020-05-27 17:45:56 +0800 [error]: config error file="/etc/fluent/fluent.conf" error_class=Fluent::ConfigError error="chunk_keys specification includes invalid char"
```

I need some help, thanks!
