### ISSUE TITLE
Producer only writes in one partition

### ISSUE THREAD

**Issue by danibeca** [fluent/fluent-plugin-kafka#339]
I have the next config for the plugin

```
<match **>
  @type kafka2
  @id out_kafka

  brokers localhost:9092
  topic_key test_topic  
  get_kafka_client_log false

  <format>
    @type  json
  </format>  
  
  max_send_retries 1
  required_acks -1
  ack_timeout nil
  compression_codec nil
  max_send_limit_bytes 6918095
  discard_kafka_delivery_failed false
</match>

```
If I'm not wrong, ruby-kafka should use the [random function](https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/partitioner.rb#L22) for choosing the partition because I'm not sending any message or partition key, but messages always go to the same partition.

I'm wondering if I'm missing any additional configuration or it's a bug in the plugin.

 Kafka Server version is 2.11-2.0.0

**Comment by repeatedly** [comment]
I tested on my local environment and it worked.

- fluentd v1.11.0
- fluent-plugin-kafka v0.13.0
- ruby-kafka 1.0.0
- kafka 2.4.0

### config

```
<source>
  @type forward
</source>

<match test.**>
  @type kafka2
  @log_level "debug"
  default_topic "test2"
  <buffer topic>
    flush_interval 5s
  </buffer>
  <format>
    @type "json"
  </format>
</match>
```

### result

```
% kafkacat -b 127.0.0.1:9092 -C -t test2 -f 'Partition: %p: Message value: %s\n'
% Reached end of topic test2 [0] at offset 0
Partition: 1: Message value: {"num":100,"message":"hi"}
% Reached end of topic test2 [1] at offset 1
Partition: 0: Message value: {"num":100,"message":"hi"}
% Reached end of topic test2 [0] at offset 1
```

Does anyone hit this issue?

**Comment by danibeca** [comment]
Hi,

I was able to find a workaround. By the way, I'm using the fluentd daemonset. I just used the random function as the ruby kafka works. For example if the amount of partitions is six, the config will be:
`partition_key "#{rand(6)}"  `

I hope this help you find the root of the problem.

Thanks for your help.

**Comment by vbottu** [comment]
I am having the same issue and I am using fluentd kafka daemonset, @danibeca I tried your workaround, it worked but it is not writing data to partition 0 and writes to other partitions

**Comment by repeatedly** [comment]
> it is not writing data to partition 0 and writes to other partitions

Because `partition_key "#{rand(6)}"` is not the solution. This parameter is interpreted like `partition_key 3` in configuration phase, `rand` is not called in data flush, and it means `kafka2` tries to get data from `"3"` field. If record doesn't have `"3"`field, `kafka2` uses default random function. It is same as default behavior and you can see default behavior works with simple configuration: https://github.com/fluent/fluent-plugin-kafka/issues/339#issuecomment-641249768

**Comment by vbottu** [comment]
The default configuration is not working for me, data always goes to partition 0, it is not sending to any other partition. I used the above workaround because of that.

**Comment by vbottu** [comment]
The default config worked for me.
