### ISSUE TITLE
Forwarding messages to different topic based on field value

### ISSUE THREAD

**Issue by kpiyush17** [fluent/fluent-plugin-kafka#343]
Hi,

I have multiple topics based on an application name like `<appname>-db`. Here appname is a field in a log.

For example:

This should go to the `fluentd-db` topic.
```
{"id":"cfcf87da-5b3e-4999-8eed-bba304e1bafa","appname":"fluentd","operation":"update"}
```

This should go to the `fluentd-test-db` topic.
```
{"id":"cfcf87da-5b3e-4999-8eed-bba304e1bafa","appname":"fluentd-test","operation":"update"}
```

Here is my current config:
```
<match **>
      @type kafka2
      @log_level debug
      brokers "localhost:9092"
      default_topic "my-topic"
      topic_key "appname"
      get_kafka_client_log "true"
      compression_codec "snappy"

      <buffer appname>
        flush_interval 5s
        chunk_limit_size 2MB
      </buffer>
      compression_codec "gzip"
</match>
```
Is this the correct way? I am not sure how to append `-db` to each appname to match the topic name. Where does that config need to be defined?

**Comment by kpiyush17** [comment]
Need help on this issue. Thanks

**Comment by repeatedly** [comment]
Patch: https://github.com/fluent/fluent-plugin-kafka/pull/347
