### ISSUE TITLE
Min ruby version 2.2 ?

### ISSUE THREAD

**Issue by max-lobur** [fluent/fluent-plugin-kafka#352]
README states
```
Ruby 2.1 or later
```
However when I install via fluent-gem (td-agent 0.12) I get
```
/opt/td-agent/embedded/bin/fluent-gem install --version 0.13.1 --no-user-install --no-document fluent-plugin-kafka
ERROR:  Error installing fluent-plugin-kafka:
	rake requires Ruby version >= 2.2.
```

**Comment by repeatedly** [comment]
fluent-plugin-kafka itself depends on ruby 2.1 or later. But recent rake gem seems to require ruby 2.2.
I'm not sure why you use too old td-agent.
We recommend to upgrade it to newer versions.
td-agent 3 uses ruby 2.4 and td-agent 4 uses ruby 2.7.
