### ISSUE TITLE
SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)

### ISSUE THREAD

**Issue by karthm12** [fluent/fluent-plugin-kafka#354]
Hi Team,

I am getting below exception , even tried to update the pem files (caroot.pem modified with  root CA alone  OR included rootCA & Intermediate CA) but still no use. Please suggest what I can do.

**Exception**:

2020-07-25 15:55:52 +0000 [info]: #0 starting fluentd worker pid=10 ppid=1 worker=0
2020-07-25 15:55:52 +0000 [info]: #0 initialized kafka producer: fluentd
2020-07-25 15:55:52 +0000 [info]: #0 following tail of /var/log/app-logs/request-response.log
2020-07-25 15:55:52 +0000 [info]: #0 fluentd worker is now running worker=0
2020-07-25 15:56:53 +0000 [warn]: #0 Send exception occurred: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
2020-07-25 15:56:53 +0000 [warn]: #0 Exception Backtrace : /usr/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.10/lib/kafka/ssl_socket_with_timeout.rb:69:in `connect_nonblock'
/usr/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.10/lib/kafka/ssl_socket_with_timeout.rb:69:in `initialize'
/usr/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.10/lib/kafka/connection.rb:127:in `new'
/usr/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.10/lib/kafka/connection.rb:127:in `open'
/usr/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.10/lib/kafka/connection.rb:98:in `block in send_request'
/usr/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.10/lib/kafka/instrumenter.rb:23:in `instrument'
/usr/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.10/lib/kafka/connection.rb:97:in `send_request'
/usr/lib/ruby/gems/2.5.0/gems/ruby-kafka-0.7.10/lib/kafka/broker.rb:200:in `send_request'

**Dockerfile**:

FROM docker.repo1.uhc.com/fluentd:v1.6.2-1.0

USER root
RUN fluent-gem install fluent-plugin-kafka
RUN fluent-gem install fluent-plugin-avro
RUN chgrp -R 0 /fluentd && \
    chmod -R g=u /fluentd
USER fluent

**fluentd.conf:** (click on edit to see readable format)

<source>
   @type tail
   path "/var/log/app-logs/request-response.log"
   tag "request-response.log"
   read_from_head true
   <parse>
     @type "json"
   </parse>
 </source>
 <filter request-response.log>
   @type record_transformer
   enable_ruby true
   auto_typecast 
   <record>
     kafka_message_key "{"clusterName":"origin-ctc-core.optum.com","namespace":"data-exts-eligibility-api-stage-ernie","podName":"eligibility-graphql-26-ffwhs","containerName":"eligibility-graphql","logFileName":"request-response.log"}"
   </record>
 </filter>
 <match *.**>
   @type kafka2
   brokers apslp1451.uhc.com:16023,ctc5hz1-01-s12.uhc.com:16023,apslp1354.uhc.com:16023,ctc5hz1-01-s10.uhc.com:16023,apslp1496.uhc.com:16023
   topic_key "class.eligibility.raw.api.request.v1"
   message_key_key "kafka_message_key"
   exclude_message_key true
   ssl_ca_cert ["/etc/fluentd/secrets/caroot.pem"]
   ssl_client_cert "/etc/fluentd/secrets/certificate.pem"
   ssl_client_cert_key "/etc/fluentd/secrets/key.pem"
   ssl_verify_hostname false
   default_topic "class.eligibility.raw.api.request.v1"
   max_send_retries 1
   required_acks -1
   compression_codec "gzip"
   <buffer topic>
     flush_interval 60s
     flush_at_shutdown true
     flush_thread_count 8
     retry_max_times 10
     retry_wait 10s
     retry_forever 
   </buffer>
   <format>
     @type "json"
   </format>
 </match>

**Comment by bazzilio** [comment]
how did you fix this ?

**Comment by karthm12** [comment]
@bazzilio ,

From my side, ca.crt contains two certificates. It seems like fluentd doesn’t like that. 
So if we split it into two files ca-root.pem and ca-intermediate.pem, then configure fluentd  like the following

 ssl_ca_cert ["/etc/fluentd/secrets/ca-intermediate.pem”, "/etc/fluentd/secrets/ca-root.pem"]
 ssl_client_cert "/etc/fluentd/secrets/certificate.pem"
 ssl_client_cert_key "/etc/fluentd/secrets/key.pem"

then worked !!!
