### ISSUE TITLE
Why discard_kafka_delivery_failed not support on kafka2 plugin

### ISSUE THREAD

**Issue by fuemoshi** [fluent/fluent-plugin-kafka#356]
hi, I meet a problem. I need to write a large number of messages to the Kafka cluster. However, sometimes the Kafka cluster is not stable. The phenomenon is that a certain partition fail to connect, resulting in a large number of buffer files. In this situation, fluentd must be restarted, and sometimes the buffer file must be deleted to make the service available. Is there any way to kick out the bad Kafka node ?

**Comment by repeatedly** [comment]
Patch: https://github.com/fluent/fluent-plugin-kafka/pull/364
