### ISSUE TITLE
Plugin outputs version for Kafka 1.1.1

### ISSUE THREAD

**Issue by evgmoskalenko** [fluent/fluent-plugin-kafka#362]
Hello, Could you tell me please which version of the plugin, I should use for Kafka 1.1.1? And the link for documentation of the plugin output for the Kafka 1.1.1 if you have.

Thanks..

**Comment by svalentino** [comment]
Not a maintainer, but I'll try to help you anyway.

The interoperability between your Kafka and the plugin is mostly "handled" in the upstream Ruby's library `ruby-kafka` (there are other lib this plugin supports, but `ruby-kafka` is the default one).

You can check which version of that library a given release of this plugin uses by checking the file `fluent-plugin-kafka.gemspec`.

You should then choose your version accordingly.

**Comment by evgmoskalenko** [comment]
Thanks.. :-)

**Comment by repeatedly** [comment]
Here is ruby-kafka document: https://github.com/zendesk/ruby-kafka#compatibility
If you don't work with ruby-kafka and your kafka version, using rdkafka output is one way.

**Comment by kenhys** [comment]
https://github.com/fluent/fluent-plugin-kafka/issues/362#issuecomment-680406095 answers it.
At least, fluent-plugin-kafka v0.14.0 or later depends on ruby-kafka 1.2.0 or later. (limited support for Kafka 1.x)
