### ISSUE TITLE
Not able to consume messages from kafka topic

### ISSUE THREAD

**Issue by ankit1mg** [fluent/fluent-plugin-kafka#372]
Hello, I am pushing json messages to Kafka using fluent bit and want to access those messages in fluentd instance. But I am not able to print messages on fluentd console. Pls find the below configuration.

```
<source>
  @type kafka
  @log_level debug
  brokers broker1:9092,broker2:9092
  topics  fluentbit-out-fluentd
  format  json
  message_key metrics
  add_prefix metrics
  @label @ES
</source>
```

```
<match **>
  @type stdout
</match>
```

```
<label @ES>
  <match **>
    @type stdout
  </match>
</label>
```

It is not throwing any error also on log files. I am using td-agent

**Comment by repeatedly** [comment]
`kafka_group` also doesn't work?

**Comment by kingprimex** [comment]
Same happening to me. If I manually 'produce' a message with kafka-producer it is consumed, but messages produced by fluent-bit are not consumed by fluent kafka...

**Comment by in-linux** [comment]
Hi
I have similar problem.
Depending on JSON message fluentd consumes messages from Kafka topic or not, and it stops consuming. When I change offset to next message, all starts correctly and working.

I have compared many JSON messages and the difference between working and problematic is just 1 word inside JSON syntax, what makes no sense or reason why it stops the fluentd.

What is interesting, the same "wrong" messages are sometimes well processed. Very strange.

----------------
Here are my source configs:
<system>
  log_level trace
</system>

<source>
  @type kafka_group
  @log_level trace
  brokers 127.0.0.1:9092
  ssl_ca_cert /fluentd/etc/certs/ca.pem
  ssl_client_cert /fluentd/etc/certs/admin.crt.pem
  ssl_client_cert_key /fluentd/etc/certs/admin.key.pem
  ssl_verify_hostname false
  format json
  consumer_group testgroup
  topics testtopic
</source>

**Comment by kenhys** [comment]
Could someone explain how to reproduce it?

**Comment by in-linux** [comment]
I have found the reason and the solution.
Reason: 
I had thousands of messages on Kafka topic and source plugin has clogged up on http queries.

Solution:
I set to process only max 3 messages at once. In my case every message had about 2000 bytes so I have set max_bytes 6600

Here are configs which works for me perfect.

<source>
  @type kafka_group
  @log_level debug
  brokers 127.0.0.1:9092
  ssl_ca_cert /fluentd/etc/certs/ca.pem
  ssl_client_cert /fluentd/etc/certs/admin.crt.pem
  ssl_client_cert_key /fluentd/etc/certs/admin.key.pem
  ssl_verify_hostname false
  format json
  consumer_group testgroup
  topics testtopic
  max_bytes 6600
  offset_commit_threshold: 3
</source>
