### ISSUE TITLE
Azure Event Hubs Kafka connection issue - cannot configure 'security.protocol'

### ISSUE THREAD

**Issue by stvflowers** [fluent/fluent-plugin-kafka#378]
I have setup the agent on Ubuntu server (td-agent) and the output to Azure Blob is working fine.

The output to Event Hubs using Kafka is not working. Kafka endpoint is enabled in Event Hubs.

These are the relevant errors in the log:

`[output:kafka:kafka.1] cannot configure 'security.protocol' property

Nov 13 14:21:22 vm-nginx td-agent-bit[12091]: [2020/11/13 14:21:22] [ warn] [output:kafka:kafka.1] fluent-bit#producer-1: [thrd:app]: 

Configuration property `sasl.mechanism` set to `PLAIN` but `security.protocol` is not configured for SASL: 

recommend setting `security.protocol` to SASL_SSL or SASL_PLAINTEXT` 

This is my OUTPUT config:

`   [OUTPUT]

        Name                      kafka  

        Match                     *  

        Brokers                   xxxxxxxxxxx.servicebus.windows.net:9093  

        Topics                    fluentbit  
        rdkafka.bootstrap.servers xxxxxxxxxxxxxxxx.servicebus.windows.net:9093 

        rdkafka.security.protocol SASL_SSL  

        rdkafka.sasl.mechanism    PLAIN  

        rdkafka.sasl.username     $ConnectionString  

        rdkafka.sasl.password     Endpoint=sb://xxxxxxxxxx.servicebus.windows.net/;......omitted`  

security.protocol is clearly set. 

Can someone help?

**Comment by StevenSalazarM** [comment]
Any new about this issue?

**Comment by agup006** [comment]
This seems to be related to Fluent Bit vs. Fluentd, is that the same for you @StevenSalazarM ?

**Comment by StevenSalazarM** [comment]
I am using Fluent Bit with output Kafka

**Comment by repeatedly** [comment]
This repository is for **fluentd** kafka plugin, not **fluent-bit** kafka plugin.
Post it on fluent-bit repository. Closed.
