### ISSUE TITLE
Kafka input plugin dont detect new topics

### ISSUE THREAD

**Issue by mrmassis** [fluent/fluent-plugin-kafka#383]
Hi everyone,
I'm using the kafka input to listem a pattern of topic.
/logaas-.*/
I'm able to listen the topics that already exist in kafka.
logaas-tenant1
logaas-tenant2
So one

My problem occur when I create a new topic. The plugin dont see it, and the dynamic perfil of approach is lost 

There are some approach to do what I wish? Create dynamic topics in a adptative way?

Tkz

**Comment by mrmassis** [comment]
Plz. This is the great importance to continues use the kafka

**Comment by kenhys** [comment]
Currently, it seems that a  pattern of topic is recognized when either startup or reconnect sequence.
we are welcome your PR.

**Comment by GiedriusS** [comment]
It should be enough to pass https://github.com/zendesk/ruby-kafka/blob/7a55dd034c7a7ce6b85ed2f3c1e1ef8d2fd49f01/lib/kafka/client.rb#L364-L366 this parameter to the consumer. I'll try adding this parameter.
