### ISSUE TITLE
warning refresh_topic_interval  is not used

### ISSUE THREAD

**Issue by wcollin** [fluent/fluent-plugin-kafka#396]
fluent version: td-agent-4.1.0-1.el7.x86_64
fluent-plugin-kafka version：fluent-plugin-kafka (0.16.0)
ruby-kafka version: ruby-kafka (1.3.0)
kafka version: kafka_2.13-2.6.1

my td-agent.conf is :
<source>
  @type kafka_group
  @log_level info

  consumer_group kafka_group
  brokers localhost:9092
  topics /test-*/
  add_prefix "kafka"
  format json
  retry_emit_limit 10
  #max_bytes               (integer) :default => 1048576
  #max_wait_time           (integer) :default => nil (Use default of ruby-kafka)
  #min_bytes               (integer) :default => nil (Use default of ruby-kafka)
  offset_commit_interval  3
  #offset_commit_threshold (integer) :default => nil (Use default of ruby-kafka)
  fetcher_max_queue_size  3000
  start_from_beginning    false
  refresh_topic_interval  10
</source>

###### Expected outcome

https://github.com/zendesk/ruby-kafka/pull/818
i need to refresh consumers to automatically subscribe to the new topics that match the regex

###### Actual outcome
the log warning parameter  'refresh_topic_interval'  in source is not used

**Comment by kenhys** [comment]
There is no such a `refresh_topic_interval` configurable parameter for `@type kafka_group`.
ref https://github.com/fluent/fluent-plugin-kafka#input-plugin-type-kafka_group-supports-kafka-group

we are welcome to your PR if you want to support it.
