### ISSUE TITLE
The secondary_file created when using the Kafka plugin fails to retransmit through the "fluent-cat command"

### ISSUE THREAD

**Issue by goslim56** [fluent/fluent-plugin-kafka#400]
I am sending data to kafka through fluentd config as below

I am accumulating logs of data that failed to be transmitted through secondary_file.

I followed the method  guided for retransmission, but only the phrase "Input must be a map (got Array)" is displayed.

[https://docs.fluentd.org/output/secondary_file](method  guided for retransmission)
Which part did I make a mistake?

====How i used flunetd-cat====
 cat /home/temp/eventqueue.log.0 | fluent-cat --format msgpack  --host 127.0.0.1 --port 24224 dev.eventqueue.*

=====my fluentd config======
![image](https://user-images.githubusercontent.com/12165782/115809131-86ab0700-a426-11eb-8fe5-6b9e41515df7.png)

**Comment by kenhys** [comment]
@goslim56 

Probably, It was fixed in fluentd v1.13.0.
ref. https://www.fluentd.org/blog/fluentd-v1.13.0-has-been-released

If there is a still trouble with it, could you provide a reproducible sample (minimum eventqueue.log.0 is better)
