### ISSUE TITLE
output_data_type single_value not working

### ISSUE THREAD

**Issue by raviprakashshahi** [fluent/fluent-plugin-kafka#41]
Hi,

Please find my confguration below, its now able to fetch the message key value from the Json

<match testlogs>
  type kafka_buffered
  zookeeper  10.100.1.36:2181
  default_topic testlogs
  flush_interval 5s
  buffer_chunk_limit 20m
  buffer_queue_limit 2000
  num_threads 1
  output_data_type single_value
  add_newline false
  message_key message
  flush_at_shutdown true
  buffer_type memory
  output_include_time false
  output_include_tag false
  disable_retry_limit false
  retry_limit 5
  <secondary>
     type file
     path /home/ubuntu/testlogs
  </secondary>
</match>

**Comment by repeatedly** [comment]
Do you still have a problem?
`single_value` works fine on my environment.

**Comment by repeatedly** [comment]
No response
