### ISSUE TITLE
Kafka .9 plugin

### ISSUE THREAD

**Issue by mohitanchlia** [fluent/fluent-plugin-kafka#44]
Does this plugin support Kafka .9? Also, our cluster has Kafka Kerberos enabled which require producers and consumers to use jaas file. Any suggestion on what need to change to accomplish this?

**Comment by htgc** [comment]
This plugin should support Kafka 0.9 also, and it can work with 0.9.
Regarding to Kerberos, this plugin doesn't support yet. let me think about it. thanks,

**Comment by repeatedly** [comment]
I'm now working on replace poseidon with ruby-kafka to support v0.9.

**Comment by apurvis** [comment]
is there a branch for that upgrade to ruby-kafka?

**Comment by drughi** [comment]
any date for 0.9 release? trying to use it with mapr streams (0.9 api ) but having problems fetching metadata from broker (for sure is the api version )

thanks mate!

**Comment by dgarros** [comment]
Hi @repeatedly, any update on the migration to ruby-kafka, is there a branch for it ?
Would be happy to help if I can

**Comment by apurvis** [comment]
0.10 is being released
https://cwiki.apache.org/confluence/display/KAFKA/Release+Plan+0.10.0

**Comment by drughi** [comment]
nice, so that version will be 0.9 kafka api compliance right? its not clear for me in the content included.

thanks!

**Comment by repeatedly** [comment]
Sorry for the delay. I opened a PR here: https://github.com/htgc/fluent-plugin-kafka/pull/54

**Comment by htgc** [comment]
thank you @repeatedly !!

**Comment by repeatedly** [comment]
`kafka_buffered` output have already supported kafka v0.9 and v0.10.
Does anyone need to support kafka v0.9 or v0.10 with input plugins.

**Comment by sanjay-varanasi** [comment]
I'd love to see Kafka 0.9 input supported, along with SSL capabilities. I'm guessing the Zookeeper config option would be dropped given that 0.9 consumer doesn't need to talk to ZK.

The ability to read a topic from the beginning would be even better, but that's for another day :)

**Comment by kentarosasaki** [comment]
Actually I need v0.10 support with input plugins.

**Comment by cynial** [comment]
@repeatedly I need the kafka v0.9 support with input plugins.

**Comment by repeatedly** [comment]
I wrote a patch for input plugins.
Please test: https://github.com/htgc/fluent-plugin-kafka/pull/64

**Comment by kentarosasaki** [comment]
@repeatedly I tested this plugin with Kafka 0.10.0 as Kafka consumer. Input plugin (@type 'kafka' and @type 'kafka_group') are working well in my environment.

**Comment by repeatedly** [comment]
@kentarosasaki Thanks for testing!

Does anyone also test the patch?
If ther is no problem, I will merge the patc and release fluent-plugi-kafka v0.3.0-dev.1

**Comment by repeatedly** [comment]
I released fluent-plugin-kafka v0.3.0.rc1 for testing.
You can install this version with `--pre` option.
Please check it on your environment before release v0.3.0.

**Comment by kentarosasaki** [comment]
@repeatedly  I've tested v0.3.0.rc1 which was installed by using `--pre` option. It's also working fine on my environment.

**Comment by repeatedly** [comment]
Thanks for the test again!

I need more tester :)

**Comment by hmmbug** [comment]
@repeatedly fwiw, I've been testing v0.3.0.rc1 today and everything looks good. I'll keep it in pre-production testing for the next few weeks.

**Comment by repeatedly** [comment]
@hmmbug thanks for the testing!

**Comment by repeatedly** [comment]
I will release fluent-plugin-kafka v0.3.0 in the end of this week.
