### ISSUE TITLE
Does this plugin support decompression when reading message from kafka?

### ISSUE THREAD

**Issue by JindongChen** [fluent/fluent-plugin-kafka#45]
Kafka support gzip, snappy, lz4 compression. Does this plugin support decompression when reading message from Kafka?

**Comment by repeatedly** [comment]
Not supported for now.
Current input plugins assumes text format.

**Comment by repeatedly** [comment]
We have already switched to ruby-kafka and it uncompresses message automatically.

https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/protocol/message_set.rb#L26

So if you use gzip/snappy in producer, input plugins handle it.
