### ISSUE TITLE
Zookeeper dependency fails on ppc64le

### ISSUE THREAD

**Issue by conaku** [fluent/fluent-plugin-kafka#46]
This fluent-plugin-kafka gem has dependency on Zookeeper and when Zookeeper dependency fails for known reason : https://github.com/zk-ruby/zookeeper/issues/79
I have been able to fix the zookeeper changes locally and am looking forward to contribute back my changes to zookeeper repository . Can someone suggest how I can build this fluent-plugin-kafka gem locally incorporating local changes of zookeeper and then be able to test fluent-plugin-kafka .

**Comment by repeatedly** [comment]
Gemfile may help you: http://bundler.io/gemfile.html

**Comment by repeatedly** [comment]
Since v0.4, zookeeper gem is optional. So it seems this problem is resolved.
