### ISSUE TITLE
Request fluent-plugin-kafka gem version update

### ISSUE THREAD

**Issue by xiao-Shu-Tiao** [fluent/fluent-plugin-kafka#493]
### Is your feature request related to a problem? Please describe.

rdkafka2 gem package not update on https://rubygems.org/gems/fluent-plugin-kafka since April 26, 2023, I want use "use_default_for_unknown_topic" new keyowrd, and old version brings some trouble to my deployment.I will be greatful if team can update on gem version.Thanks.

### Describe the solution you'd like

update gem package version

### Describe alternatives you've considered

build on local

**Comment by xiao-Shu-Tiao** [comment]
I have packaged the latest version of the gem package called `fluent-plugin-kafka-xst`, which includes the `use_default_for_unknown_topic` feature of the latest rdkafka, and can be installed using `gem install fluent-plugin-kafka-xst`. I hope the official can do it as soon as possible Pack new features, thanks!

**Comment by ashie** [comment]
I've released v0.19.1. Sorry for my late response.

**Comment by xiao-Shu-Tiao** [comment]
> I've released v0.19.1. Sorry for my late response.

thanks for your updating~
