### ISSUE TITLE
Kafka::LeaderNotAvailable

### ISSUE THREAD

**Issue by alanyee** [fluent/fluent-plugin-kafka#67]
```
{"message":"Kafka::LeaderNotAvailable"}
{"host":"192.168.0.11","port":24224,"hard_timeout":true,"message":"detached forwarding server '192.168.0.11:24224' host=\"192.168.0.11\" port=24224 hard_timeout=true"}
{"host":"192.168.0.12","port":24224,"hard_timeout":true,"message":"detached forwarding server '192.168.0.12:24224' host=\"192.168.0.12\" port=24224 hard_timeout=true"}
```

What does  this mean?

**Comment by alanyee** [comment]
Also would anyone happen to know how to stop fluentd? I do not know how to kill/restart the process.

**Comment by repeatedly** [comment]
> LeaderNotAvailable

This said the cause. fluent-plugin-kafka can't find the leader for topic/partition.

**Comment by alanyee** [comment]
Oh I figured out the error, but I am not still not sure if there is an easier way to kill the fluentd process besides looking up the PID and then running the kill command.

**Comment by repeatedly** [comment]
>  if there is an easier way to kill the fluentd process besides looking up the PID and then running the kill command.

If you use fluentd directly, not td-agent, then using kill command is needed because fluentd is typical daemon process.

http://docs.fluentd.org/articles/signals
http://docs.fluentd.org/articles/rpc
