### ISSUE TITLE
Doesn't detect newly added logs ocassionally

### ISSUE THREAD

**Issue by pirasakat** [fluent/fluent-plugin-kafka#69]
Kafka version: kafka_2.11-0.9.0.1
fluent-plugin-kafka : 0.3.0

Hi, guys

With very latest version `0.3.0`, the plugin sometimes doesn't detect newly added logs and doesn't send them to my kafka. Sometimes added logs are sent to kafka, and sometimes aren't. Very irregular.
It worked fine with older version `0.1.3`.

My `/etc/td-agent/td-agent.conf` is something like this. 

```
<source>
  @type       tail
  format      none
  path        /var/log/app.log
  pos_file    /var/log/app.log.pos
  message_key body
  tag         test_tag
</source>

<match test_tag>
  @type            kafka
  brokers          broker001:9092
  default_topic    test_topic
  output_data_type json
</match>
```

Thanks

Toru

**Comment by repeatedly** [comment]
> the plugin sometimes doesn't detect newly added logs and doesn't send them to my kafka.

What does this sentence mean?
You use `kafka` output, so it means your consumer can't get several logs?

**Comment by pirasakat** [comment]
Yes, I tried to consume logs from kafka with both `kafka-console-consumer.sh` and `kafka-simple-consumer-shell.sh`.

**Comment by repeatedly** [comment]
Are there no error logs in fluentd log?

**Comment by pirasakat** [comment]
No, there aren't any error logs.

**Comment by pirasakat** [comment]
OK, let me tell you what I did more in detail.

I added new lines by using command `cat several_lines.log >> /var/log/app.log`.
Right after adding lines, sometimes I could consume the whole lines from kafka.
But sometimes not.

**Comment by repeatedly** [comment]
I tested `out_kafka` with my consumer(https://github.com/treasure-data/kafka-fluentd-consumer) and there is no problem.
So I think kafka-console-consumer / kafka-simple-consumer-shell have a problem.

**Comment by repeatedly** [comment]
Ah, wait. I need more time to investigate the problem deeply.

**Comment by repeatedly** [comment]
This problem doesn't happen with `kafka_buffered`, right?

**Comment by pirasakat** [comment]
I haven't tried the kafka_buffered yet.

**Comment by repeatedly** [comment]
If you want to use kafka plugin on production, kafka_buffered is recommended.
`kafka` output is only for testing.

**Comment by repeatedly** [comment]
It seems the problem is default `required_acks 0` setting.
Set `required_acks 1`, the problem seems to be resolved.
Could you try `required_acks 1` on your environment?

**Comment by pirasakat** [comment]
All right, then l will try kafka_buffered and see if it works.
Since l'm out of office now, let me get back to you tomorrow.

**Comment by repeatedly** [comment]
Thanks.
I continue to investigate why `kafka` output have a problem with `required_acks 0`.

**Comment by pirasakat** [comment]
Thank you for quick responses!

**Comment by pirasakat** [comment]
As you mentioned, it worked fine with `required_acks 1` option.
Thank you, repeatedly!

**Comment by pirasakat** [comment]
As you mentioned, it worked fine with required_acks 1 option.
Thank you, repeatedly!

**Comment by repeatedly** [comment]
Thanks for testing! I just changed default behaviour.
