### ISSUE TITLE
It seems to be buffer full when I set flush_interval more than 2 seconds

### ISSUE THREAD

**Issue by jamesweb1** [fluent/fluent-plugin-kafka#7]
I try to set flush_interval not so frequently as 5 second, but my client always says javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated. I guess it rejects by fluentd's source. I try to increase the buffer as follows:
   *buffer_chunk_limit 512m
   *buffer_queue_limit 64
It's the same thing. But I set flush_interval to 2, it works fine with no loss. Can anyone give me the hint??

**Comment by repeatedly** [comment]
Old issues. Closed.
