### ISSUE TITLE
Lost messages, strange buffer files after upgrading

### ISSUE THREAD

**Issue by dtboctor** [fluent/fluent-plugin-kafka#78]
We recently bumped our version of the plugin to the latest on Sept 21.  

Later on when trying to consolidate data we realized a lot of data from that day is missing, and when I go to our folders where we are storing the buffers for fluentd I see a bunch of strange "..*.log" files from that day that I can't explain

```
Wed Oct 05 09:56:20 [6:0]$ ls -lah
total 1.4M
drwxr-xr-x. 2 lumoslabs lumoslabs 4.0K Oct  5 09:56 .
drwxr-xr-x. 4 root      root        41 Jul 14 16:42 ..
-rw-r--r--. 1 root      root       93K Sep 21 14:01 ..b53d0adad2c926a4e.log
-rw-r--r--. 1 root      root       78K Oct  5 09:56 buffer.b53e210e8a540d529c7409b2af3b263c8.log
-rw-r--r--. 1 root      root        75 Oct  5 09:56 buffer.b53e210e8a540d529c7409b2af3b263c8.log.meta
-rw-r--r--. 1 root      root      1.1M Oct  5 09:56 buffer.q53e210df2541167ab5cede2521dd8af6.log
-rw-r--r--. 1 root      root        77 Oct  5 09:56 buffer.q53e210df2541167ab5cede2521dd8af6.log.meta
```

Do these files contain our lost data?  (Specifically the `..b53d0adad2c926a4e.log` file).  Are they indicative that something broke, and can we get any data that might be in there out of there?   Is there a different procedure we should follow when bumping our version to prevent any chance of data loss?

**Comment by repeatedly** [comment]
I'm not sure why these files are not flushed but ".log" files contain buffered events.

**Comment by repeatedly** [comment]
You have 2 pattern log files, "..b53d0adad2c926a4e.log" and "buffer.b53e210e8a540d529c7409b2af3b263c8.log".
I assume you updated fluentd to v0.14 or changed buffer_path parameter.

**Comment by dtboctor** [comment]
Yeah, it looks like fluentd was bumped, would that have left those files.  Is there any way to get those uploaded?   Was the new version of fluentd incompatible with the old buffer files?

**Comment by repeatedly** [comment]
> Yeah, it looks like fluentd was bumped

We recommend to pin the fluentd / plugin version for stable deployment.

> Is there any way to get those uploaded.

One way is moving old buffer files to other directly and using fluentd v0.12 to reload it.
Another way is reading buffer file and re-post it to fluentd via fluent-logger.

> Was the new version of fluentd incompatible with the old buffer files?

Yes. fluentd v0.14 has new buffer mechanizm for more robustness and flexibility.
Hard to v0.12 buffers to v0.14 because v0.12 buffer doesn't have metadata in it.

**Comment by dtboctor** [comment]
I'm going to close this since it isn't really an issue with this plugin.
