### ISSUE TITLE
remove message key 

### ISSUE THREAD

**Issue by ahsandar** [fluent/fluent-plugin-kafka#84]
in `out` `kakfa_buffered` can the `message` key be removed so raw data is captured 
instead of `{"message": [json]}` we just get `[json]`

**Comment by repeatedly** [comment]
You can use `output_data_type single_value`

**Comment by ahsandar** [comment]
Thanks

**Comment by ahsandar** [comment]
`output_data_type` `single_value` doesn't seem to do the trick,  ant change it is 
`format` `single_value`

**Comment by repeatedly** [comment]
What does "output_data_type single_value doesn't seem to do the trick" mean?
You can't get "[json]" by `output_data_type single_value`?

**Comment by ahsandar** [comment]
still getting `{"message":" [json]}` with   `output_data_type` `single_value`, `message` key seems to be there for messages sent to `kafka`

**Comment by ahsandar** [comment]
```
output_data_type single_value
output_include_tag false
```

passing `output_include_tag` `false` explicitly along `output_data_type` `single_value` did the trick
