### ISSUE TITLE
message_key parameter not working 

### ISSUE THREAD

**Issue by ankurjha7** [fluent/fluent-plugin-kafka#96]
The "message_key" parameter is not populating the value in the "key" parameter of kafka message.

**Comment by repeatedly** [comment]
This issue is unclear.
Please write more detailed information here.

**Comment by ankurjha7** [comment]
I am modifying my record before forwarding the same to kafka plugin 

<filter cart_access>
  @type record_transformer
  <record>
    message_key ${cartKey}
  </record>
</filter>

And the kafka plugin configuration is as follows 

<match cart_access>
@type kafka

zookeeper       localhost:2181
default_topic         cart_data
</match>

Ideally the the value of message_key should be sent as key for kafka message . But when i consume the kafka message the key is coming as null.

**Comment by repeatedly** [comment]
Plugin has no problem, so closed for now.
If you have a complete reproducible step with actual dataset, configuration and environment list,
reopen this issue.
